[goto-check] Remove __ESBMC prefix
esbmc/esbmc pull request #1001
Opened 2023-05-03 20:23 UTC by brcfarias

This PR fixes #999.

2023-05-03 20:28 UTC, brcfarias commented
The sample code is available [here](https://github.com/esbmc/esbmc/blob/381413c5fa287296eb938e389fc3283b49b79a00/regression/cstd/scanf-bug/main.c)

2023-05-03 21:50 UTC, mikhailramalho requested changes
We actually have code to do that in expr2c or expr2cpp.

They've been broken for a while, so we should fix and use them here instead.

2023-05-05 08:13 UTC, lucasccordeiro approved these changes

2023-05-05 08:14 UTC, rafaelsamenezes approved these changes

2023-05-05 08:41 UTC, merged

2023-05-05 08:41 UTC, lucasccordeiro commented
Many thanks, @brcfarias.