[CUDA] refactor/modify the COM
esbmc/esbmc pull request #1111
Opened 2023-06-20 19:49 UTC by XLiZHI

In the old model there was a circular dependency problem where `cuda.h` and `cuda_runtime_api.h` files contained each other, which should be avoided in C++.

Purpose: Including too much unused code can lead to a large AST, which is not good for debugging, and we need to separate different functions to ensure simplicity.

`cuda.h`:  Interact directly with CUDA hardware, such as memory management and device synchronization.

`cuda_runtime_api.h`: The runtime API automatically handles many common operations, such as memory allocation.

2023-06-20 19:57 UTC, lucasccordeiro requested changes

2023-06-20 19:57 UTC, lucasccordeiro commented on src/cpp/library/CUDA/vector_types.h
> +  *                                                                              *
We should remove these headers.

2023-06-20 19:57 UTC, lucasccordeiro commented on src/cpp/library/CUDA/vector_types.h
> +  *                                                                              *
We should remove these headers.

2023-06-20 20:32 UTC, lucasccordeiro approved these changes
Many thanks, @XLiZHI.

2023-06-20 21:05 UTC, kunjsong01 requested changes

2023-06-20 21:05 UTC, kunjsong01 commented on src/cpp/library/CUDA/cuda.h
> +cudaError cudaMalloc(void **devPtr, size_t size)
Would it be possible to double check the return type for cudaXYZ APIs? 
They seem to return `cudaError_t` instead of `cudaError`. 

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g37d37965bfb4803b6d4e59ff26856356

2023-06-20 21:05 UTC, kunjsong01 commented on src/cpp/library/CUDA/cuda.h
> +cudaError cudaThreadSynchronize()
Doesn't this API return cudaError_t rather than cudaError? 
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__THREAD__DEPRECATED.html#group__CUDART__THREAD__DEPRECATED_1g86ba4d3d51221f18a9a13663e6105fc1

2023-06-20 21:25 UTC, XLiZHI commented on src/cpp/library/CUDA/cuda.h
> +cudaError cudaThreadSynchronize()
Yes, it should return `cudaError_t`, but in the API `cudaError_t `and `cudaError` are same and they do exactly the same thing. I will change them back to be consistent with the official documentation. Thanks for your advises.

2023-06-21 13:47 UTC, kunjsong01 approved these changes

2023-06-21 13:48 UTC, merged

2023-06-21 13:48 UTC, lucasccordeiro commented
Many thanks, @XLiZHI.