Added OM sanity check TCs
esbmc/esbmc pull request #1141
Opened 2023-06-30 11:33 UTC by kunjsong01

Done work for https://github.com/esbmc/esbmc/issues/1140

2023-06-30 12:25 UTC, lucasccordeiro requested changes

2023-06-30 12:25 UTC, lucasccordeiro commented on regression/esbmc-cpp/OM_sanity_checks/algorithm/test.desc
> +-I /__w/esbmc/esbmc/src/cpp/library --memlimit 14000000 --timeout 900
Do we really need this?

2023-06-30 13:44 UTC, kunjsong01 commented on regression/esbmc-cpp/OM_sanity_checks/algorithm/test.desc
> +-I /__w/esbmc/esbmc/src/cpp/library --memlimit 14000000 --timeout 900
removed

2023-06-30 13:59 UTC, lucasccordeiro approved these changes
Many thanks, @kunjsong01.

2023-07-01 06:30 UTC, lucasccordeiro approved these changes

2023-07-01 06:30 UTC, merged