Fix temporary object constructs for a single argument
esbmc/esbmc pull request #1196
Opened 2023-07-15 07:55 UTC by XLiZHI

This PR optimizes the generation of temporary objects.

2023-07-15 12:35 UTC, XLiZHI commented
goto-functions
before:
```
main (c:@F@main#):
        // 32 
        FUNCTION_CALL:  dim3(( dim3 *)1, 1, 1)
```

now:
```
main (c:@F@main#):
        // 34 file main.cpp line 16 column 3 function main
        dim3 tmp$1;
        // 35 no location
        FUNCTION_CALL:  dim3((unsigned int)(&tmp$1), 1, 1, 1)
        // 36 
        tmp$1;
```

2023-07-15 15:25 UTC, lucasccordeiro approved these changes

2023-07-15 15:47 UTC, kunjsong01 commented
> goto-functions before:
> 
> ```
> main (c:@F@main#):
>         // 32 
>         FUNCTION_CALL:  dim3(( dim3 *)1, 1, 1)
> ```
> 
> now:
> 
> ```
> main (c:@F@main#):
>         // 34 file main.cpp line 16 column 3 function main
>         dim3 tmp$1;
>         // 35 no location
>         FUNCTION_CALL:  dim3((unsigned int)(&tmp$1), 1, 1, 1)
>         // 36 
>         tmp$1;
> ```

The first parameter in the `FUNCTION_CALL` doesn't look quite right... I reckon it should be just `&tmp$1`

2023-07-15 15:53 UTC, XLiZHI commented
> The first parameter in the `FUNCTION_CALL` doesn't look quite right... I reckon it should be just `&tmp$1`

I did the same with before we deal with the `case clang: : Stmt: : CXXTemporaryObjectExprClass`, this means that there is a problem with the previous processing.

2023-07-15 16:00 UTC, kunjsong01 commented
>Do you have any suggestions?

We need to know where the`(unsigned int)` typecasting comes from, and probably need to avoid it in this case.

2023-07-17 17:31 UTC, kunjsong01 requested changes
1. Do we really need to support `assert(dim3(3).z == 1);` ?   
2. Even if we really want to support it, we probably should do it in the adjuster, instead of the converter. 

![Screenshot 2023-07-17 at 17 59 17](https://github.com/esbmc/esbmc/assets/32592800/61ee7f05-1c57-4e12-a989-7c1cb8a39235)

The converter has done a pretty good job w.r.t temporaries. We just need to adjust the statements from
```
        dim3 return_value$_dim3$1;
        // 35 
        FUNCTION_CALL:  return_value$_dim3$1=dim3(( dim3 *)3, 1, 1)
```
to 
```
        dim3 return_value$_dim3$1;
        // 35 
        FUNCTION_CALL:  dim3(( dim3 *)(&return_value$_dim3$1), 3, 1, 1)
```

2023-07-17 17:31 UTC, kunjsong01 commented on regression/esbmc-cpp/bug_fixes/1176_issue/main.cpp
> +  assert(dim3(3).x == 3);
Is `assert(dim3(3).z == 1);` mimicking any syntax or semantics in CUDA OM that's blocking us? 

If not, I'd suggest close this PR, and probably better to add a representative test case in 1189 and just focus on that PR. 

It's probably not the best thing to do to overcomplicates the code based on some edge cases. This is going to affect our debugging, maintanence and future extensions.

2023-07-17 17:59 UTC, XLiZHI commented
> 1. Do we really need to support `assert(dim3(3).z == 1);` ?   
> 2. Even if we really want to support it, we probably should do it in the adjuster, instead of the converter. 
> 
> ![Screenshot 2023-07-17 at 17 59 17](https://github.com/esbmc/esbmc/assets/32592800/61ee7f05-1c57-4e12-a989-7c1cb8a39235)
> 
> The converter has done a pretty good job w.r.t temporaries. We just need to adjust the statements from
> ```
>         dim3 return_value$_dim3$1;
>         // 35 
>         FUNCTION_CALL:  return_value$_dim3$1=dim3(( dim3 *)3, 1, 1)
> ```
> to 
> ```
>         dim3 return_value$_dim3$1;
>         // 35 
>         FUNCTION_CALL:  dim3(( dim3 *)(&return_value$_dim3$1), 3, 1, 1)
> ```
> 

Would you mind checking the difference between the current master and this patch here again, I think you may have labelled it incorrectly.

2023-07-17 18:45 UTC, kunjsong01 commented
>Would you mind checking the difference between the current master and this patch here again, I think you may have labelled it incorrectly.

Nope, it's labelled correctly.
Since we had another merge to the master in past few hours, I'll just lablel it "master", instead of "current master". 

Here's the GOTO diffs between master vs. this patch(cc42cc49) and master vs. this patch (2de9367e1bc9, just one more commit from cc42cc49). 

![Screenshot 2023-07-17 at 19 27 39](https://github.com/esbmc/esbmc/assets/32592800/e42ed845-535a-4ac4-8bab-a209fc203e38)

![Screenshot 2023-07-17 at 17 59 17](https://github.com/esbmc/esbmc/assets/32592800/964908d6-c0bb-4e14-87c4-057f96e5828d)

What's really needs to be noticed here is that there's nothing wrong with the existing temporary creation for `CXXFunctionalCastExprClass` with a subexpression `CXXConstructExpr`. 

The current master is doing a pretty good job at it. Also, the temporary object has already been created as part of removing side effect flow in `goto_sideeffects.cpp` (we know `return_value$` is from the goto conversion right?). So we don't need to give a special case for `CXXFunctionalCastExprClass` and simply follow what we have for `CXXTemporaryObjectExprClass`. 

If we really need to support the TCs in this PR and to do it in the ESBMC-way,  please consider doing some proper adjustments in either: 
1. adjuster
2. goto converter (probably as part of the removing side effect flow in goto_sideeffects.cpp)

2023-07-19 09:29 UTC, kunjsong01 requested changes
Also, is there any new TCs to verify the code changes in this patch?

2023-07-19 09:29 UTC, kunjsong01 commented on src/goto-programs/goto_sideeffects.cpp
>      // for copy constructor, we need to add the implicit `this` as the first argument,
we probably need to update this comment too ;)

2023-07-19 09:29 UTC, kunjsong01 commented on src/clang-cpp-frontend/clang_cpp_convert.cpp
>    // Add to the list of params
It's probably better to update the comment here. "// Add `this` as the first parameter to the list of params". 
Or just move it if you wish, the code seems pretty self-explanatory.

2023-07-19 09:54 UTC, kunjsong01 commented
We should add back the TC with `assert(dim3(3).x == 3); ` and compare the GOTO programs generated. Once this is verified, the patch is good to go. Otherwise, we kinda lose track of what we want to fix with this patch.

2023-07-19 12:01 UTC, kunjsong01 requested changes

2023-07-19 12:01 UTC, kunjsong01 commented on regression/esbmc-cpp/bug_fixes/1176_issue/test.desc
> +^VERIFICATION SUCCESSFUL$
The test case looks great! 
We just need one more TC for the "VERIFICATION FAILED" counterpart. `assert(dim3(3).z == 3); // should be 1` should do. 
Edit: ~~Also, would it be possible to add the old GOTO vs. new GOTO you've collected and shared in the slack channel? Those are pretty good information to show the manin purpose of this PR~~ Already done in the description.

2023-07-19 12:07 UTC, kunjsong01 approved these changes

2023-07-19 14:54 UTC, merged

2023-07-19 14:54 UTC, lucasccordeiro commented
Thanks for submitting this PR, @XLiZHI.