[libm] Replaced existing operational models with MUSL library
esbmc/esbmc pull request #1232
Opened 2023-07-28 11:05 UTC by emanino

The existing libm operation models were incomplete and, in at least two cases, incorrect. First, acos(x) was wrongly implemented as 1/cos(x) instead of the inverse of the cosine function. Second, pow(x, y) assumed that y was the floating-point representation of an integer number, hence pow(2.1, 3.4) would actually return pow(2.1, 3.0). Third, many functions used imprecise, iterative implementations (e.g. cos(x), sqrt(x)) which were slow to verify and not bit-precise. Fourth, many important functions in the families of exponentials, logarithms, hyperbolic, trigonometric, Bessel, Gaussian and Gamma were not implemented.

This pull request provides operational models for all libm functions in three variants: float, double and long double. The operational models are ported from the MUSL libraryand written in plain C. In particular, we chose the MUSL library over Newlib and other similar libraries because its implementation guarantees correct roundings and contains as few loops as possible. Finally, the MUSL library is released under the MIT license.

2023-07-28 11:21 UTC, fbrausse commented
> In particular, we chose the MUSL library over Newlib and other similar libraries because its implementation guarantees correct roundings

Hi @emanino, thank you for this PR! I wonder whether you could point me to any additional resources that support this claim. In particular, do you know of verification efforts or correctness proofs regarding musl's libm?

2023-07-28 12:55 UTC, emanino commented
> > In particular, we chose the MUSL library over Newlib and other similar libraries because its implementation guarantees correct roundings
> 
> Hi @emanino, thank you for this PR! I wonder whether you could point me to any additional resources that support this claim. In particular, do you know of verification efforts or correctness proofs regarding musl's libm?

Hi Franz, thanks for the question. I do not think there has been verification efforts on MUSL. My claims comes from the following sources.

One of the authors of MUSL found bugs in GCC while working on a bit-precise implementation of sqrt(x). See:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52593

MUSL was designed to be compliant to the standard, and a lot of effort was put towards such goal. See:
https://wiki.musl-libc.org/mathematical-library.html

A comparison table between different libraries can be found at the following link. See "features comparison" and "C99 math library":
https://www.etalabs.net/compare_libcs.html

As far as I know, there is currently an academic effort towards correct rounding by the CORE-MATH project. Unfortunately their library is incomplete and contains some bugs (I had a wrong result using their exp(x) function). It may be worth keeping an eye on their progress in the near future. Still, I do not know if they verify or prove the correctness of their implementation. See:
https://core-math.gitlabpages.inria.fr/

2023-07-28 13:00 UTC, fbrausse commented
I know Core-math and Paul Zimmermann, he's one of the main authors of MPFR. Many thanks for the additional pointers @emanino!

2023-07-28 14:56 UTC, mikhailramalho requested changes
Thanks for the PR @emanino, however, I have a few concerns that must be addressed before this PR can be approved:
1. ESBMC encodes some operations internally using the SMT API (from the top of my head, I remember sqrt and fma, but there might be others). Calling these functions directly should be faster than the code implemented here. Is there a reason to replace them, e.g., performance, correctness?
2. Some of the iterative algorithms were only used in fixedbv arithmetic (via the __ESBMC_FIXEDBV ifdef), does the new algorithms you've added still work with fixedbvs?
3. We need test cases for all new models.

2023-07-28 14:58 UTC, rafaelsamenezes commented
- Reachability run (this PR): https://github.com/esbmc/esbmc/actions/runs/5691144790
- Reachability run (from last week): https://github.com/esbmc/esbmc/actions/runs/5643389166

The PR is fixing some KNOWNBUGs:
- esbmc/math_exp01
- esbmc/math_exp02
- esbmc/math_exp03

@emanino could you replace the KNOWNBUG to CORE (inside test.desc)?

However, the build time is taking too long. Even the action job is being cancelled automatically for taking too long.

My guess is that c2goto (and esbmc) have the problem of having to parse everything sequentially. @emanino How hard would be to mix the files into a few big C file?

2023-07-28 15:10 UTC, fbrausse commented
> How hard would be to mix the files into a few big C file?

If that's the problem, we could just add one libm.c file which #includes all the other .c files.

2023-07-28 15:19 UTC, rafaelsamenezes commented
> If that's the problem, we could just add one libm.c file which #includes all the other .c files.

True, I will do a PR to test this out.

2023-07-28 16:41 UTC, emanino commented
> Thanks for the PR @emanino, however, I have a few concerns that must be addressed before this PR can be approved:
> 
>     1. ESBMC encodes some operations internally using the SMT API (from the top of my head, I remember sqrt and fma, but there might be others). Calling these functions directly should be faster than the code implemented here. Is there a reason to replace them, e.g., performance, correctness?
> 
>     2. Some of the iterative algorithms were only used in fixedbv arithmetic (via the __ESBMC_FIXEDBV ifdef), does the new algorithms you've added still work with fixedbvs?
> 
>     3. We need test cases for all new models.

Hi Mikhail, that is great feedback! I have some further question though.

1. Is there some documentation on which operations are encoded internally? Even just a list would be great. Also, how does ESBMC decide between using the internal operation vs the external operational model? How is the conflict resolved?
2. Similarly, is there any documentation on fixedbv arithmetic? I am guessing it stands for "fixed bit vectors", but I have never encountered the term before. Is it meant to model some specific IEEE 754 behaviour? The MUSL library assumes 32-bit floats and 64-bit doubles. Long doubles are either 64-bit or 80-bit. See the documentation at https://wiki.musl-libc.org/mathematical-library.html
3. Until now, I trusted the code in the MUSL library, since it is part of several Linux distribution. Are there tests for the old operational models in ESBMC I can draw inspiration from?

Many thanks in advance.

2023-07-28 18:42 UTC, mikhailramalho commented
> 1. Is there any documentation on which operations are encoded internally? Even just a list would be great. Also, how does ESBMC decide between using the internal operation vs the external operational model? How is the conflict resolved?

I don't think so... there are a few places you can look for them: the irep2 types, the do_special_functions in the frontend, and the fp encoding on backend.

> 2. Similarly, is there any documentation on fixedbv arithmetic? I am guessing it stands for "fixed bit vectors", but I have never encountered the term before. Is it meant to model some specific IEEE 754 behaviour? The MUSL library assumes 32-bit floats and 64-bit doubles. Long doubles are either 64-bit, 80-bit or 128-bit. See the documentation at https://wiki.musl-libc.org/mathematical-library.html

fixedbv is another way of encoding real numbers that brings some advantages/disadvantages compared to IEEE floating points. You can find more information about them in Lucas' and mine thesis. 

> 3. Until now, I trusted the code in the MUSL library, since it is part of several Linux distributions. Are there tests for the old operational models in ESBMC I can draw inspiration from?

Yes, you can find them in regressions/floats and regressions/floats-regression. Basically, when I wrote them you need to work out a test case with constants and another with nondet values, that way we can check if the simplification is not doing anything wrong with the models.

Also, remember that it's not only about trusting the correctness of the code but also if esbmc can handle the code you're writing efficiently. We are not executing code, but encoding it in SMT, so code that would be faster in one case not necessarily be the best approach for the other. That's also why we always run the PRs on SV-Comp and check for regressions there too (wrong results, timeouts, etc).


> 
> Many thanks in advance.

2025-08-15 22:12 UTC, lucasccordeiro commented
This PR is no longer valid.

2025-08-15 22:12 UTC, closed without merging