replace pow() recursion with loop
esbmc/esbmc pull request #1364
Opened 2023-09-20 22:10 UTC by Anthonysdu

esbmc cannot finish unrolling the recursion in `pow()` function, and also doesn't work with `--unwindset` because it doesn't have a loopid.
```
int main() {
  int res = pow(2, 4);
  assert(res == 16);
}
```
Shall we replace the recursion with the loop?

2023-09-20 23:43 UTC, lucasccordeiro requested changes
@Anthonysdu: can you please add regression tests?

2023-09-21 06:51 UTC, fbrausse commented
This is the wrong implementation. The `pow` function is supposed to compute a double-precision approximation of x ** y, i.e., exp(log(x) * y). Certain range reductions like log(x) = 2 * log(sqrt(x)) could be done iteratively when working with an exact representation, but y itself is not an integer and cannot be treated as such by a loop.

2023-09-21 10:57 UTC, Anthonysdu commented
> This is the wrong implementation. The `pow` function is supposed to compute a double-precision approximation of x ** y, i.e., exp(log(x) * y). Certain range reductions like log(x) = 2 * log(sqrt(x)) could be done iteratively when working with an exact representation, but y itself is not an integer and cannot be treated as such by a loop.

I see, thanks

2023-10-09 11:03 UTC, emanino commented
@Anthonysdu if you need a double-precision operational model of pow(), have a look at
https://github.com/esbmc/esbmc/pull/1232

2023-10-31 13:04 UTC, fbrausse commented
#1421 has landed, which includes an unrolled version of the exponentiation-by-squaring method patched in this PR. @Anthonysdu Shall we close this PR?

2023-10-31 13:08 UTC, closed without merging