[multi-property] performance improvement
esbmc/esbmc pull request #1605
Opened 2024-01-20 00:28 UTC by ChenfengWei0

- file.c
```c
int main()
{
    for(int i =0 ; i<10;i++)
        for(int j =0 ; j<10; j++)
            for(int k =0 ; k<10; k++)
                for(int l =0 ; l<10; l++)
                    assert(i+j+k>l);
}
```
- command: `./esbmc file.c --unwind 12 --multi-property`
- result (debug version)
```sh
# Before
./esbmc file.c --unwind 12 --multi-property  50.69s user 0.55s system 99% cpu 51.267 total
# After
./esbmc file.c --unwind 12 --multi-property  13.25s user 0.56s system 99% cpu 13.844 total
```
- The output is also simplified, no more annoying "Found verified claim. Skipping..."

2024-01-20 01:15 UTC, lucasccordeiro commented
This is a very nice PR :-). 

@Anthonysdu: could you please review this PR?

2024-01-20 01:56 UTC, Anthonysdu commented
Cool, this can help remove a lot of unnecessary claims!

2024-01-20 16:42 UTC, lucasccordeiro commented
@Anthonysdu: could you please run this PR over the RMM project?

2024-01-20 16:58 UTC, Anthonysdu commented
> @Anthonysdu: could you please run this PR over the RMM project?

The master branch cannot process the rmm code since PR #1602 :
```
Converting
Generating GOTO Program
GOTO program creation time: 3.414s
Computing Value-Set Analysis (VSA)
Segmentation fault (core dumped)
```
PR #1601 :

```
Converting
Generating GOTO Program
GOTO program creation time: 3.419s
Computing Value-Set Analysis (VSA)
GOTO program processing time: 7.505s
Starting Bounded Model Checking
WARNING: no body for function __builtin_clzll
WARNING: no body for function __builtin_clzll
Unwinding loop 53 iteration 1   file 
```

2024-01-20 21:40 UTC, rafaelsamenezes commented
> > @Anthonysdu: could you please run this PR over the RMM project?
> 
> The master branch cannot process the rmm code since PR #1602 :
> 
> ```
> Converting
> Generating GOTO Program
> GOTO program creation time: 3.414s
> Computing Value-Set Analysis (VSA)
> Segmentation fault (core dumped)
> ```
> 
> PR #1601 :
> 
> ```
> Converting
> Generating GOTO Program
> GOTO program creation time: 3.419s
> Computing Value-Set Analysis (VSA)
> GOTO program processing time: 7.505s
> Starting Bounded Model Checking
> WARNING: no body for function __builtin_clzll
> WARNING: no body for function __builtin_clzll
> Unwinding loop 53 iteration 1   file 
> ```

Hm it may be an issue from https://github.com/esbmc/esbmc/pull/1391

2024-01-20 21:49 UTC, rafaelsamenezes commented
@Anthonysdu could you check if this PR solves the issues: https://github.com/esbmc/esbmc/pull/1607?

Also, it would be great if you could generate a test case that is causing the performance degradation

2024-01-20 22:05 UTC, rafaelsamenezes requested changes

2024-01-20 22:05 UTC, rafaelsamenezes commented on src/goto-symex/slice.h
> +  bool run(symex_target_equationt::SSA_stepst &, bool show_slice_info);
I  think that moving `show_slice_info` to inside the class would be better.

2024-01-20 22:05 UTC, rafaelsamenezes commented on src/esbmc/bmc.cpp
> +    std::string cmt_loc = claim.claim_msg + "\t" + claim.claim_loc;
For the future we should consider moving to a proper hashing algorithm.

2024-01-20 22:11 UTC, rafaelsamenezes commented
Great addition, I would suggest moving the logic to here: https://github.com/esbmc/esbmc/blob/d966de633efccd2074aa53b4904631ad66a747bc/src/esbmc/bmc.cpp#L735

Mainly because:

1. I don't think you need to rely on the claim slicer to get the assert. You can get it directly from VCC.
2. The list of jobs should be filtered before, specially if we want for this to eventually work in parallel.

2024-01-21 11:43 UTC, Anthonysdu commented
> @Anthonysdu could you check if this PR solves the issues: #1607?
> 
> Also, it would be great if you could generate a test case that is causing the performance degradation

```
Converting
Generating GOTO Program
GOTO program creation time: 2.989s
Segmentation fault (core dumped)
```
It still happens, but can get rid of it if disable `--interval-analysis`

2024-01-21 12:26 UTC, lucasccordeiro commented
@Anthonysdu: can you test this PR performance without the interval analysis enabled?

2024-01-21 12:27 UTC, Anthonysdu commented
> @Anthonysdu: can you test this PR performance without the interval analysis enabled?

Yes, doing it

2024-01-21 12:30 UTC, lucasccordeiro commented
Thank you.

2024-01-21 13:22 UTC, rafaelsamenezes commented
> > @Anthonysdu could you check if this PR solves the issues: #1607?
> > 
> > Also, it would be great if you could generate a test case that is causing the performance degradation
> 
> ```
> Converting
> Generating GOTO Program
> GOTO program creation time: 2.989s
> Segmentation fault (core dumped)
> ```
> It still happens, but can get rid of it if disable `--interval-analysis`

I guess we should move to a new issue. Could you run with a debugger and return the back trace

2024-01-21 13:31 UTC, fbrausse approved these changes
Nice! LGTM. If the log-message now hidden by `show_slice_info` actually is important, I'd suggest to use the Debug log-level for it instead of not showing it at all. If it's not important (I didn't check), I'd suggest to remove it entirely, instead.

2024-01-21 15:29 UTC, lucasccordeiro commented
@ChenfengWei0: could you please adddress @fbrausse's suggestion?

2024-01-22 00:42 UTC, ChenfengWei0 commented on src/goto-symex/slice.h
> +  bool run(symex_target_equationt::SSA_stepst &, bool show_slice_info);
Changed as suggested

2024-01-22 00:43 UTC, ChenfengWei0 commented
> Nice! LGTM. If the log-message now hidden by `show_slice_info` actually is important, I'd suggest to use the Debug log-level for it instead of not showing it at all. If it's not important (I didn't check), I'd suggest to remove it entirely, instead.

Added a `log_debug()` as suggested

2024-01-22 04:37 UTC, Anthonysdu commented
```
before:
			claims		time(s)
RMI_REC_DESTROY		113		2579.9
RMI_GRANULE_DELEGATE	54		357.7
RMI_GRANULE_UNDELEGATE	45 		289.1
RMI_REALM_ACTIVATE	53		530.4
RMI_REALM_DESTROY	114		1659.8
RMI_REC_AUX_COUNT	48 		507
RMI_FEATURES		21 		276.8
RMI_DATA_DESTROY	82		>5000

This PR:
			claims		time(s)
RMI_REC_DESTROY		84		1477.3
RMI_GRANULE_DELEGATE	54		394.8
RMI_GRANULE_UNDELEGATE	45 		341.2
RMI_REALM_ACTIVATE	53		503.5
RMI_REALM_DESTROY	72		792.2
RMI_REC_AUX_COUNT	48 		441.9
RMI_FEATURES		21 		210.4
RMI_DATA_DESTROY	117		>5000
```

claims in two testcases `rec_destory` and `realm_destory` are reduced.

2024-01-22 07:55 UTC, lucasccordeiro commented
Many thanks, @Anthonysdu. What about the number of safe and unsafe cases reported by esbmc? Did they change?

2024-01-22 07:56 UTC, lucasccordeiro approved these changes

2024-01-22 09:26 UTC, fbrausse commented
> claims in two testcases `rec_destory` and `realm_destory` are reduced.

But RMI_DATA_DESTROY did go up. @ChenfengWei0 Do you know why they might go up with this PR?

2024-01-22 09:42 UTC, Anthonysdu commented
> > claims in two testcases `rec_destory` and `realm_destory` are reduced.
> 
> But RMI_DATA_DESTROY did go up. @ChenfengWei0 Do you know why they might go up with this PR?

This case, the previous run did not stop in 7 hours (if you could remember), and the new run was killed by system in 2 hours because out of 16GB memory, so actually both run did not finish.

We also have the run realm_destory being killed twice. And this PR reports more bugs in the two cases and I need to confirm them.

2024-01-22 12:12 UTC, merged

2024-01-22 12:13 UTC, lucasccordeiro commented
Thanks for submitting this PR, @ChenfengWei0. Well done!