[C++ VERIFICATION] Improved cpp new and delete
esbmc/esbmc pull request #1648
Opened 2024-02-06 14:14 UTC by XLiZHI

Fixed C++ dangling pointer checking. 

Fixed C++ double delete.

Next PR todo: move the adjustment of cpp new and delete into symex.

2024-02-06 15:34 UTC, lucasccordeiro requested changes
I have two comments here.

2024-02-06 15:34 UTC, lucasccordeiro commented on regression/esbmc-cpp/cpp/ dangling_ptr/test.desc
> +^VERIFICATION SUCCESSFUL$
There is a memory leak in this program.

Can you please create another test case that enables --memory-leak-leak?

2024-02-06 15:34 UTC, lucasccordeiro commented on regression/esbmc-cpp/cpp/ dangling_ptr/main.cpp
> +
Can you also create another test case that adds the delete to mark it as VERIFICATION SUCCESSFUL?

2024-02-06 16:30 UTC, lucasccordeiro approved these changes

2024-02-06 19:57 UTC, fbrausse approved these changes
You can unify both branches by casting `*code2` to the common base class `const code_expression_data &`. Otherwise LGTM.

2024-02-07 05:34 UTC, XLiZHI commented
> You can unify both branches by casting `*code2` to the common base class `const code_expression_data &`. Otherwise LGTM.

Hi @fbrausse,

Thanks for your advice, I tried this, but cmake complained about it.
```
const code_expression_data &deref_code = is_code_cpp_delete2t(code2)? to_code_cpp_delete2t(code2)
                                                                    : to_code_cpp_del_array2t(code2);
```
different types ‘code_cpp_delete2t’ and ‘code_cpp_del_array2t’. Or do we have a general type cast function?

2024-02-07 07:44 UTC, fbrausse commented
`const auto &code_expr = static_cast<const code_expression_data &>(*code2);` should work.

2024-02-07 07:49 UTC, XLiZHI commented
> const auto &code_expr = static_cast<const code_expression_data &>(*code2);

Great, thanks

2024-02-07 07:54 UTC, merged

2024-02-07 07:54 UTC, lucasccordeiro commented
Thanks for submitting this PR, @XLiZHI.