[solidity] Fix the missing contract name in the symbol id
esbmc/esbmc pull request #1697
Opened 2024-02-21 10:50 UTC by ChenfengWei0

Fix the missing contract name in the symbol id.

```solidity
contract Base
{
    function test() public
    {
        uint xx;
    }
}

```

Result:
```sh
#before
sol:@C@@F@test@xx#13
#after
sol:@C@Base@F@test@xx#13
```

Thank you for raising this issue, @JacobYiu !

2024-03-22 11:12 UTC, lucasccordeiro requested changes
@ChenfengWei0 : can you please add some test cases that cover the many changes introduced to this PR?

2024-03-23 00:46 UTC, ChenfengWei0 commented
> @ChenfengWei0 : can you please add some test cases that cover the many changes introduced to this PR?

Add regression test cases as suggested.

2024-03-23 05:43 UTC, lucasccordeiro approved these changes

2024-03-23 05:43 UTC, merged

2024-03-23 05:44 UTC, lucasccordeiro commented
Thanks for submitting this PR, @ChenfengWei0.