[clang-cpp-frontend] Simplify if conditions
esbmc/esbmc pull request #1756
Opened 2024-03-20 09:03 UTC by XLiZHI

New functions are used to simplify the if condition.

2024-03-26 23:50 UTC, fbrausse requested changes
I also thought about a change like this when looking into the reference handling, and I'm sure fine with it. Except: could we please stick to the lower-case function identifiers?

2024-03-27 12:51 UTC, fbrausse approved these changes
Thanks, LGTM.

2024-03-27 12:55 UTC, lucasccordeiro approved these changes

2024-03-27 13:07 UTC, merged

2024-03-27 13:07 UTC, lucasccordeiro commented
Thanks for submitting this PR, @XLiZHI.