Fix recursive structs in templates #1782
esbmc/esbmc pull request #1783
Opened 2024-04-14 18:51 UTC by intrigus-lgtm

2024-04-15 00:22 UTC, mikhailramalho requested changes
It doesn't look like you need to add the extra argument in the c and cpp frontend. Also always add an explanation of your PR

2024-04-15 00:22 UTC, mikhailramalho commented on regression/esbmc-cpp/bug_fixes/1782/test.desc
> +^ERROR: CONVERSION ERROR
Just add an empty main here and make the test pass.

2024-04-15 00:22 UTC, mikhailramalho commented on src/clang-c-frontend/clang_c_convert.cpp
> +  if (only_forward_declare)
Can't you just call isThisDeclarationADefinition() here?

2024-04-15 00:22 UTC, mikhailramalho commented on src/clang-cpp-frontend/clang_cpp_convert.cpp
> +  bool OnlyForwardDeclare)
Or maybe check D->isThisDeclarationADefinition() here?

2024-04-15 22:58 UTC, intrigus-lgtm commented
> It doesn't look like you need to add the extra argument in the c and cpp frontend. Also always add an explanation of your PR

Apologies, I should have opened this as a draft instead.

2024-09-18 14:21 UTC, lucasccordeiro commented
@intrigus-lgtm: Can I ask you for the status of this PR?

2024-09-18 21:01 UTC, intrigus-lgtm commented
> @intrigus-lgtm: Can I ask you for the status of this PR?

I don't think this PR fixes the problem in the long run.
In the branch I use for my work, I used @fbrausse's https://github.com/esbmc/esbmc/pull/819 PR + some additional fixes and it works pretty well, but it's too intertwined with my other stuff to upstream it easily and without taking a lot of my time.

2024-12-03 12:05 UTC, lucasccordeiro commented
@intrigus-lgtm: Can I ask you for the status of this PR?

2025-01-09 15:16 UTC, lucasccordeiro commented
@intrigus-lgtm: Can I ask you for the status of this PR?

2025-01-10 14:19 UTC, intrigus-lgtm commented
> @intrigus-lgtm: Can I ask you for the status of this PR?

If you want, you can close this. I don't think it would be merged as is.
One could cleanup and salvage the TCs.

2025-08-15 22:36 UTC, lucasccordeiro commented
Thanks, @intrigus-lgtm.

I have the test cases of this PR here https://github.com/esbmc/esbmc/commit/b4a01c4698762688ad9c6eda6b98066e1f4068e2.

2025-08-15 22:36 UTC, closed without merging