[Solidity] Bug fixed for constructor and struct
esbmc/esbmc pull request #1788
Opened 2024-04-21 15:08 UTC by ChenfengWei0

```solidity

/////////////// bug 1

Contract x = new Contract(); // ok
Contract x; // segfault

/////////////// bug 2

struct T {
  uint[2] x;
}

T xx = {[1,2]};
xx.x[0]; // wrong value
```

2024-04-21 18:27 UTC, lucasccordeiro requested changes

2024-04-21 18:27 UTC, lucasccordeiro commented on src/solidity-frontend/solidity_convert.cpp
> +    const std::string contract_name =
Can you add a comment like "// Extract contract name"?

2024-04-21 18:27 UTC, lucasccordeiro commented on src/solidity-frontend/solidity_convert.cpp
> +    if (get_implicit_ctor_call(val, contract_name))
Add a comment here too something like "Check if there's an implicit constructor call for the contract"

2024-04-21 18:27 UTC, lucasccordeiro commented on src/solidity-frontend/solidity_convert.cpp
> +    solidity_gen_typecast(ns, val, t);
// Generate typecast for Solidity contract

2024-04-21 18:27 UTC, lucasccordeiro commented on src/solidity-frontend/solidity_convert.cpp
> +    decl.operands().push_back(val);
Add constructor call to declaration operands?

2024-04-21 18:27 UTC, lucasccordeiro commented on regression/esbmc-solidity/inheritance_7/test.desc
> +^VERIFICATION SUCCESSFUL$
Can you add a version that produces ``VERIFICATION FAILED''?

2024-04-21 18:27 UTC, lucasccordeiro commented on regression/esbmc-solidity/struct_5/test.desc
> +^VERIFICATION SUCCESSFUL$
Can you add a version that produces ``VERIFICATION FAILED''?

2024-04-21 18:27 UTC, lucasccordeiro commented on regression/esbmc-solidity/struct_6/test.desc
> +^VERIFICATION SUCCESSFUL$
Can you add a version that produces ``VERIFICATION FAILED''?

2024-04-21 18:27 UTC, lucasccordeiro commented on regression/esbmc-solidity/struct_7/test.desc
> +^VERIFICATION SUCCESSFUL$
Can you add a version that produces ``VERIFICATION FAILED''?

2024-04-22 13:58 UTC, ChenfengWei0 commented
Changed as suggested

2024-04-22 14:25 UTC, lucasccordeiro approved these changes
Thanks for submitting this PR, @ChenfengWei0.

2024-04-22 14:56 UTC, merged