[Coverage] Fix the strategy and testcase generation for coverage
esbmc/esbmc pull request #2066
Opened 2024-10-10 15:11 UTC by ChenfengWei0

2024-10-10 15:23 UTC, lucasccordeiro requested changes
@ChenfengWei0: could you please add some regression tests?

2024-10-11 13:05 UTC, ChenfengWei0 commented
> @ChenfengWei0: could you also please add some regression tests in C++?

Done

2024-10-11 13:29 UTC, lucasccordeiro approved these changes

2024-10-11 14:32 UTC, intrigus-lgtm requested changes

2024-10-11 14:32 UTC, intrigus-lgtm commented on regression/goto-coverage/Testing/Temporary/LastTest.log
What is this needed for?

2024-10-11 17:56 UTC, ChenfengWei0 commented on regression/goto-coverage/Testing/Temporary/LastTest.log
Local ctest log file. Forgot to delete…

2024-10-12 05:31 UTC, merged

2024-10-12 05:31 UTC, lucasccordeiro commented
Thanks for submitting this PR, @ChenfengWei0.