Added timestamp and location to LOG messages
esbmc/esbmc pull request #2097
Opened 2024-10-25 08:35 UTC by Chriszai

Added timestamps and locations to log messages to address #886.

2024-10-25 09:04 UTC, rafaelsamenezes requested changes
Thanks for the PR. It looks like a good direction, could you:

1. Check if its possible to just preapend at the format string in https://github.com/esbmc/esbmc/blob/master/src/util/message.h#L73 that way you will not need to do as many changes. 
2. As suggested at https://github.com/esbmc/esbmc/issues/886#issuecomment-1463333671 we need this to be a flag or env variable opt-in.

2024-10-25 18:47 UTC, mikhailramalho commented
How does the log looks like after your change?

2024-10-29 08:39 UTC, Chriszai commented
> Thanks for the PR. It looks like a good direction, could you:
> 
> 1. Check if its possible to just preapend at the format string in https://github.com/esbmc/esbmc/blob/master/src/util/message.h#L73 that way you will not need to do as many changes.
> 2. As suggested at [Add timestamp and location to LOG messages #886 (comment)](https://github.com/esbmc/esbmc/issues/886#issuecomment-1463333671) we need this to be a flag or env variable opt-in.

1. Yes, I've already made all the changes in message.h.
2. I've opted it in as a flag, and users can use `--log-message` as an option.

2024-10-29 08:44 UTC, Chriszai commented
> What does the log look like after your change?

For example, if the user turns on the option `--log-message`, the log will look like `VERIFICATION SUCCESSFUL File: /home/ESBMC_Project/esbmc/src/esbmc/bmc.cpp, Line: 210 [2024-10-29 16:30:21] ` when verification is successful.

2024-10-29 18:49 UTC, mikhailramalho requested changes
I don't like the time being appended and would prefer it to be prepended. This is more the standard in other tools, like journalctl, dmesg, etc.

Let's hear from the other developers about the format before landing this.

2024-10-29 18:49 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +  {
no need for curly brackets here.

2024-10-29 18:49 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
>    }
is this just code style? We have to check if it's the same version used in our CI.

2024-10-29 19:29 UTC, rafaelsamenezes approved these changes
I also prefer the time to be preappended. Otherwise lgtm.

2024-10-29 19:47 UTC, lucasccordeiro approved these changes
I also agree with @mikhailramalho's suggestions. Please address them before we merge this PR, @Chriszai.

2024-10-29 19:54 UTC, lucasccordeiro commented
@Chriszai: can you also please fix the code style issue here?

2024-10-30 09:05 UTC, Chriszai commented
> @Chriszai: can you also please fix the code style issue here?

Yes, sure

2024-10-30 10:00 UTC, lucasccordeiro commented
CI is still failing, @Chriszai.

2024-10-30 13:02 UTC, lucasccordeiro commented
CI is still failing, @Chriszai.

2024-10-30 13:02 UTC, lucasccordeiro commented
![image](https://github.com/user-attachments/assets/5ac734f1-53f5-4b76-a1e0-6ce234c16eea)

2024-10-30 13:03 UTC, lucasccordeiro commented
````
error: Your local changes to the following files would be overwritten by checkout:
	src/esbmc/options.cpp
	src/util/message.h
Please commit your changes or stash them before you switch branches.
Aborting
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v5/index.js:17:19)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v5/index.js:17:19)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
````

2024-10-30 17:16 UTC, Chriszai commented
I guess it has nothing to do with my code, but with the git workflow

2024-10-30 18:25 UTC, lucasccordeiro commented
Thanks, @Chriszai.

@mikhailramalho: do you still have further comments about this PR?

2024-10-31 10:28 UTC, lucasccordeiro requested changes

2024-10-31 10:28 UTC, lucasccordeiro commented on src/util/message.h
>          fmt::print(f, "[{}] File: {}, Line: {} ", timeStr, file, line);
@Chriszai: According to @mikhailramalho's comments, should you move `timeStr` to the beginning, or did I miss something here?

2024-10-31 13:15 UTC, ChrisCheng816 commented on src/util/message.h
>          fmt::print(f, "[{}] File: {}, Line: {} ", timeStr, file, line);
Yes, I have moved `timeStr` to the beginning; during the verification process, timestamp will be output first (as shown in the line 84), followed by LOG messages (as shown in the line 86).

```
fmt::print(f, "[{}] File: {}, Line: {} ", timeStr, file, line);
println(f, lvl, format, fmt::make_format_args(args...));
```

2024-10-31 13:35 UTC, lucasccordeiro commented
Thanks for this explanation!

2024-10-31 13:36 UTC, lucasccordeiro commented
![image](https://github.com/user-attachments/assets/c822d7c0-9f2f-4676-81aa-b505c89abe03)

2024-10-31 14:23 UTC, rafaelsamenezes commented
@Chriszai could you please rebase your code on top of master (we have a guide here: https://github.com/esbmc/esbmc/blob/master/CONTRIBUTIONS.md#contributing-to-the-code-base). After that we should be able to merge.

2024-10-31 15:27 UTC, mikhailramalho approved these changes
LGTM

2024-10-31 15:44 UTC, Chriszai commented
![image](https://github.com/user-attachments/assets/d41c9d4f-cb55-4805-acda-ec622a66904c)
My fork is already updated; still cannot be merged?

2024-10-31 15:52 UTC, lucasccordeiro commented
@Chriszai: We're still unable to merge your PR.

Did you try to follow the steps indicated by @rafaelsamenezes?

2024-11-01 08:09 UTC, closed without merging