Feature/json report
esbmc/esbmc pull request #2127
Opened 2024-11-09 06:55 UTC by sshivaji

Slimmer PR for just JSON report for ESBMC

2024-11-09 17:44 UTC, mikhailramalho requested changes
Please go through Rafael's comment from the last PR. Stuff like global variables, leftover comments, and unnecessary includes need to be fixed.

2024-11-09 19:34 UTC, sshivaji commented
Thx @mikhailramalho, I have made changes

2024-11-10 09:50 UTC, rafaelsamenezes requested changes
Just one comment. Otherwise LGTM.

2024-11-10 09:50 UTC, rafaelsamenezes commented on src/goto-symex/json.cpp
> +            starts_with(std::filesystem::path(file_path).string(), "/usr/")) {
I think you are the same check a few times now. Consider adding a function and documenting why the /usr is the only prefix to check

2024-11-11 07:06 UTC, sshivaji commented
Now updated for codacy and @rafaelsamenezes's comments, thanks!

2024-11-11 18:25 UTC, lucasccordeiro approved these changes

2024-11-11 18:38 UTC, ChenfengWei0 approved these changes
Overall LGTM, just some minor correction

2024-11-11 18:38 UTC, ChenfengWei0 commented on src/goto-symex/json.cpp
> +            log_status("Error: Could not open report.json for writing");
Same as above

2024-11-11 18:38 UTC, ChenfengWei0 commented on src/goto-symex/json.cpp
> +                    log_status("Error parsing existing report.json: {}", e.what());
Same as above

2024-11-11 18:38 UTC, ChenfengWei0 commented on src/goto-symex/json.cpp
> +                    log_status("Serialization error: {}", e.what());
`log_error()` might be more appropriate for this case

2024-11-11 18:38 UTC, ChenfengWei0 commented on src/goto-symex/json.cpp
> +                    log_status("Error processing step: {}", e.what());
Same as above

2024-11-11 18:38 UTC, ChenfengWei0 commented on src/goto-symex/json.cpp
> +                        log_status("Error reading file {}: {}", file, e.what());
Same as above

2024-11-11 18:41 UTC, sshivaji commented on src/goto-symex/json.cpp
> +                        log_status("Error reading file {}: {}", file, e.what());
Thanks, will def change to this

2024-11-11 18:44 UTC, sshivaji commented on src/goto-symex/json.cpp
> +                        log_status("Error reading file {}: {}", file, e.what());
Done!

2024-11-12 07:28 UTC, merged

2024-11-12 07:29 UTC, lucasccordeiro commented
Thanks for submitting this PR, @sshivaji.