[Concurrency] Partial Order Reduction
esbmc/esbmc pull request #2188
Opened 2024-12-10 04:38 UTC by Anthonysdu

2024-12-11 09:13 UTC, lucasccordeiro requested changes

2024-12-11 09:13 UTC, lucasccordeiro commented on src/goto-symex/reachability_tree.cpp
> +  if (get_cur_state().threads_state[0].thread_ended)
I agree here, but I would suggest submitting this change to another PR so we can understand its effect.

2026-01-04 18:14 UTC, lucasccordeiro commented
@Anthonysdu: do you still have plans to work on this PR?

2026-05-27 10:35 UTC, closed without merging

2026-05-27 10:36 UTC, Anthonysdu commented
Closed via #4696