add cex-only && simplify-trace options
esbmc/esbmc pull request #2208
Opened 2024-12-27 01:16 UTC by ChenfengWei0

- `cex-only`: `do not print the state trace`
- `simplify-trace`: `do not output the assignments that are not from user-input files`

The `simplify-trace` can work with options like `compact-trace` and `cex-only`

2024-12-27 13:38 UTC, lucasccordeiro approved these changes

2024-12-27 15:51 UTC, intrigus-lgtm reviewed
Not a big fan of adding all those ifs everywhere.
Is there no cleaner way or possibility to put all those checks into a single place?

2024-12-28 13:08 UTC, lucasccordeiro requested changes

2024-12-28 13:08 UTC, lucasccordeiro commented on src/goto-symex/goto_trace.cpp
> +  if (file != "")
You could improve this code. For example:

````CPP
void appendInfo(std::string &dest, const std::string &label, const std::string &value)
{
    if (!value.empty())
    {
        if (!dest.empty())
            dest += " ";
        dest += label + " " + id2string(value);
    }
}

if (!file.empty())
    appendInfo(dest, "file", file);

if (!line.empty())
    appendInfo(dest, "line", line);

if (!function.empty())
    appendInfo(dest, "function", function);
````

2024-12-28 13:09 UTC, lucasccordeiro commented
> Is there no cleaner way or possibility to put all those checks into a single place?

I agree with @intrigus-lgtm. I have added one suggestion here.

2025-01-01 08:23 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
> +  if (file != "")
Changed as requested

2025-01-01 09:51 UTC, lucasccordeiro approved these changes
Thanks for submitting this PR, @ChenfengWei0.

2025-01-01 09:51 UTC, lucasccordeiro commented
@intrigus-lgtm: are you happy with this PR version?

2025-01-02 00:14 UTC, intrigus-lgtm requested changes
Some things that could simplify this even more.

2025-01-02 00:14 UTC, intrigus-lgtm commented on src/goto-symex/goto_trace.cpp
> +          !input_file_check(step.pc->location.get_file().as_string()))
I would assume that this can fail with a segfault when a step's location does not have an associated file (or is this actually impossible?).
Especially for C++, where we generate quite some code for vtables and other stuff, we didn't really generate any locations for the code (It's also unclear what location to use for constructs that have no source-code location).

2025-01-02 00:14 UTC, intrigus-lgtm commented on src/goto-symex/goto_trace.cpp
> +// Return true if the file is from the user-input
What is user-input for you?

I personally would not have considered include files as user-input.
As said in another comment, some instructions don't have any location.

2025-01-02 00:14 UTC, intrigus-lgtm commented on src/goto-symex/goto_trace.cpp
> +        if (!cex_only)
Why do we not show a state header in this case?
If `--show-stacktrace` and `--cex-only` are passed, we still show a stack trace, but no state header?

2025-01-02 00:14 UTC, intrigus-lgtm commented on src/goto-symex/goto_trace.cpp
>    {
Can't we simplify the code to this?
This should allow us to remove all those `if(!cex_only)` statements.
```suggestion
  for (const auto &step : goto_trace.steps)
  {
    // we only care about the counter example, which is only triggered by assert steps. Ignore all other steps.
    if (cex_only && step.type != goto_trace_stept::ASSERT)
      continue;
```

2025-01-06 08:44 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
> +          !input_file_check(step.pc->location.get_file().as_string()))
I believe it has a default value `""`.

2025-01-06 08:49 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
> +// Return true if the file is from the user-input
> What is user-input for you?

```c++
input_file = options.get_option("input-file");
include_files = cmdline.get_values("include-file");
```

> some instructions don't have any location

I am not sure why we need to worry about the instructiont that has no file location. If it has no location, then it will be simplified, since it's internally created rather than user-input

2025-01-06 08:54 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
> +        if (!cex_only)
> Why do we not show a state header in this case?

Cex-only: do not print the state trace.

> If --show-stacktrace and --cex-only are passed, we still show a stack trace, but no state header?

show-stacktrace: show function call trace. E.g.
```sh
# --show-stack-trace --cex-only

[Counterexample]

Violated property:
  file 1.c line 3 column 22 function reach_error
Stack trace:
  c:@F@reach_error at file 1.c line 1646 column 11 function ssl3_connect
  c:@F@ssl3_connect at file 1.c line 1076 column 3 function main
  c:@F@main
  assertion 0
  0


VERIFICATION FAILED

Bug found (k = 7)
```

2025-01-06 08:57 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
> +// Return true if the file is from the user-input
The idea is to only print out the trace step that is related to the files provided by the user

2025-01-06 09:03 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
>    {
Changed as suggested

2025-01-06 14:10 UTC, intrigus-lgtm commented on src/goto-symex/goto_trace.cpp
> +// Return true if the file is from the user-input
Internally created instructions can exist in user-provided files.

E.g. all code related to vtable initialization is internally created from user-provided files.

2025-01-06 14:37 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
> +// Return true if the file is from the user-input
Sorry for not having the background knowledge of the vtable initialization.

> ll code related to vtable initialization is internally created from user-provided files.

Are these "code related to vtable initialization" already in the input files before feeding into ESBMC? If so, why does it not having a file location? If not, e.g. inserted in the frontend/GOTO stage, I believe it should be filtered.

2025-01-06 14:40 UTC, ChenfengWei0 commented on src/goto-symex/goto_trace.cpp
> +// Return true if the file is from the user-input
Also if the location is missing, it will confuse our users anyway.

2025-02-28 16:25 UTC, lucasccordeiro commented
@intrigus-lgtm: Do you still have comments about this PR?

2025-03-01 09:15 UTC, merged

2025-03-01 09:15 UTC, lucasccordeiro commented
Thanks for submitting this PR, @ChenfengWei0.