Incremental context bound verification
esbmc/esbmc pull request #233
Opened 2020-06-29 17:28 UTC by lucasccordeiro

This PR adds support for incremental context-bound verification for multi-threaded C programs.

I have run this PR using different values to `context-bound-step` and `max-context-bound` using the SV-COMP benchmarks. The best results were obtained using the following parameters:

```
--incremental-cb
--context-bound-step 5 (starting at 2, 7, 12)
--max-context-bound 15
--no-por
--unwind 8
```

As a result, I have obtained the following results:

Before this PR:

```
Statistics:           1082 Files
  correct:             967
    correct true:      182
    correct false:     785
  incorrect:            21
    incorrect true:     14
    incorrect false:     7
  unknown:              94
  Score:               589 (max: 1344)
```

After this PR:

```
Statistics:           1082 Files
  correct:             876
    correct true:      102
    correct false:     774
  incorrect:             5
    incorrect true:      2
    incorrect false:     3
  unknown:             201
  Score:               866 (max: 1344)
```

2020-06-30 15:29 UTC, mikhailramalho requested changes
Looks almost fine. I didn't understand why you changed several lines in the option descriptions: if it was you IDE, check if the max column is set to less than 80.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +    else if(!do_forward_condition(opts, goto_functions, unwind))
no need for an `else` here.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +
No need for the variable `unknown` in this code.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "by "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "encoding\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "symbolic "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "calls\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "conversions\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "witness "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "(default)\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "verification\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "is "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "UINT_MAX\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "arithmetic\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "symbol "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "step "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "is "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "UINT_MAX\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "approach\n"
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "verification\n"
Check if the line fits the 80 columns.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "is 2)\n"
This looks broken, check if the line fits the 80 columns.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "15)\n"
This looks broken, check if the line fits the 80 columns.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "UINT_MAX\n"
Check if the line fits the 80 columns.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "\"100m\" "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "assumes "
No need to change this line.

2020-06-30 15:29 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +    opts.set_option("context-bound", str);
why are you using snprintf here? Check how we set the unwind option in methods like `do_base_case`.

2020-06-30 16:51 UTC, mikhailramalho requested changes
Overall, I didn't like this approach because it is not compatible with incremental bmc, e.g., if the user sets --incremental-bmc, the incremental context-bound will be ignored.

I think the loop to increment the context bound should be moved the methods that call each step `do_inductive_step`, `do_forward_condition` and `do_base_case`).

2020-06-30 16:51 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "is 2)\n"
the `is 2)` still looks broken.

2020-06-30 16:51 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +       "15)\n"
the `15)` still looks broken.

2020-06-30 16:51 UTC, mikhailramalho commented on src/esbmc/esbmc_parseoptions.cpp
> +
The use of the `unknown` variable still looks confusing. 

We are repeatedly calling the forward condition step, without changing the number of loop unwinding. Could you add an example where changing the number of context switches makes the forward condition report the wrong result?

Furthermore, we only set `unknown` to false if the forward condition is false, if it is true, shouldn't we set `unknown` to true? I mean, if for context bound = 2 the forward condition set `unknown` to false, but in context bound = 3 the forward condition doesn't hold, we are still reporting that the verification is not unknown.

Either unknown should be part of the branch condition to call the forward condition or the forward condition should be performed after we finished incrementing the context bound.

2020-06-30 18:36 UTC, mikhailramalho reviewed
Much better! We are almost there:
1. Could you add the same logic to the steps in the k-induction parallel?
2. Now that the incremental-context-bound is not incompatible with the incremental-bmc, we should support cases where the user did not set the unwind or set it to a fixed value: this can be done by adding the proper logic at the end of the `doit()` method, surrounding: 
```
  // do actual BMC
  bmct bmc(goto_functions, opts, context, ui_message_handler);
  set_verbosity_msg(bmc);
  return do_bmc(bmc);
}
```

2020-07-23 13:23 UTC, lucasccordeiro commented
@fatimahkj: Could you please take a look at this PR?

2020-07-23 13:27 UTC, lucasccordeiro commented
@kaled-alshmrany: This is the issue.

2020-08-24 22:35 UTC, mikhailramalho approved these changes
LGTM

2020-08-25 03:28 UTC, feliperodri approved these changes
LGTM too.

2020-08-25 12:23 UTC, merged