add operational model for pthread_detach
esbmc/esbmc pull request #242
Opened 2020-07-16 15:48 UTC by fatimahkj

This PR contains the operational model for the pthread_detach function. 

Signed-off-by: fatimahkj <fatimahaljaafari@gmail.com>

2020-07-16 16:02 UTC, rafaelsamenezes requested changes

2020-07-16 16:02 UTC, rafaelsamenezes commented on src/c2goto/library/pthread_lib.c
> +    det != 0, "You want to detach a thread which already detached");
Just a nitpick here. You are declaring the variable `det` that is only once used, use the value directly. I would change the error message to:

"Detaching a detached thread is Undefined Behaviour"

2020-07-16 16:02 UTC, rafaelsamenezes commented on src/c2goto/library/pthread_lib.c
> +  return 0;
The reference defines three return values:

- 0: When no error occurred
- EINVAL:  thread is not a joinable thread.
- ESRCH:  No thread with the ID thread could be found.

2020-07-17 10:01 UTC, lucasccordeiro commented
@fatimahkj: Test case `01_pthread67` is failing in our CI. Could you please check it?

2020-07-17 13:07 UTC, lucasccordeiro requested changes
I think we should have something like:

```
// The pthread_detach() marks the thread identified by thread as detached.
// source: https://man7.org/linux/man-pages/man3/pthread_detach.3.html
int pthread_detach(pthread_t threadid)
{
__ESBMC_HIDE:;
  __ESBMC_atomic_begin();

  if(__ESBMC_pthread_thread_detach[(int)threadid])
    return EINVAL; //  thread is not a joinable thread.
  if(!__ESBMC_pthread_thread_running[(int)threadid])
    return ESRCH; // No thread with the ID thread could be found.
  __ESBMC_terminate_thread();
  __ESBMC_pthread_thread_detach[(int)threadid] = 1;
  __ESBMC_atomic_end();

  return 0; // no error occurred
}
```

2020-07-17 16:29 UTC, lucasccordeiro commented
@fatimahkj: I believe you would need to write five test cases to check your implementation as follows:

thread is not a joinable thread.
```
assert(pthread_detach(some_thread_id) == EINVAL)
```

thread is a joinable thread.
```
assert(pthread_detach(some_thread_id) != EINVAL)
```

No thread with the ID thread could be found.
```
assert(pthread_detach(some_thread_id) == ESRCH)
```

Thread with the ID thread could be found.
```
assert(pthread_detach(some_thread_id) != ESRCH)
```

// no error occurred
```
assert(pthread_detach(some_thread_id) == 0)
```

2020-07-18 16:50 UTC, lucasccordeiro commented
Closed via https://github.com/esbmc/esbmc/pull/243.

2020-07-18 16:50 UTC, closed without merging