Fix recursion bomb in the k-induction algorithm
esbmc/esbmc pull request #249
Opened 2020-08-19 12:53 UTC by mikhailramalho

The k-induction algorithm tries to get all the variables inside every loop, however, we were only recursion case where a function calls itself, not if we have a recursion cycle from function a to b then back to a.

This PR fixes the issue by keeping a list of function calls and checking if we already entered a given function before. We also pop the function call from the list when we hit a return.

Fixes issue #248.

2020-08-19 13:42 UTC, lucasccordeiro requested changes
Two minor comments:

1) Could you please add a test case to this PR? e.g., a test case that succeeds and another one that fails
2) Could you also please rebase your branch? Otherwise, you won't be able to merge it into master.

2020-08-22 15:31 UTC, mikhailramalho commented
New fix solves issues #248  and #252

2020-08-22 19:00 UTC, pmatos commented
The fix works - `numarith.c` from racket seems to be verified without crashes with k-induction.

2020-08-23 12:27 UTC, lucasccordeiro approved these changes
@mikhailramalho: I have just one minor comment for this PR.

2020-08-23 12:27 UTC, lucasccordeiro commented on regression/esbmc/github_248/test.desc
> +KNOWNBUG
Should it be declared as `CORE`?

2020-08-25 01:50 UTC, merged