Fix global expression (EXPERIMENTAL & DO NOT MERGE)
esbmc/esbmc pull request #400
Opened 2021-03-01 12:36 UTC by lucasccordeiro

2021-03-01 20:06 UTC, lucasccordeiro commented
Master:

```
<benchmark tool="esbmc" timelimit="15 min" memlimit="15 GB" cpuCores="1">
```

```
if concurrency:
  esbmc_dargs += "--no-por --context-bound 2"
  esbmc_dargs += "--no-slice "
```

```
Statistics:           1130 Files
  correct:             966
    correct true:      181
    correct false:     785
  incorrect:            17
    incorrect true:     12
    incorrect false:     5
  unknown:             147
  Score:               683 (max: 1413)
```

This PR:

```Statistics:           1130 Files
  correct:             967
    correct true:      182
    correct false:     785
  incorrect:            18
    incorrect true:     13
    incorrect false:     5
  unknown:             145
  Score:               653 (max: 1413)
```

2021-03-02 08:22 UTC, lucasccordeiro commented
```
<benchmark tool="esbmc" timelimit="15 min" memlimit="15 GB" cpuCores="1">
```

```
if concurrency:
  esbmc_dargs += "--no-por --context-bound 3"
  esbmc_dargs += "--no-slice "
```

```
Statistics:           1130 Files
  correct:             965
    correct true:      180
    correct false:     785
  incorrect:            16
    incorrect true:     10
    incorrect false:     6
  unknown:             149
  Score:               729 (max: 1413)
```

2021-03-03 14:30 UTC, lucasccordeiro commented
This PR: 

```
<benchmark tool="esbmc" timelimit="15 min" memlimit="15 GB" cpuCores="1">
```

```
if concurrency:
  esbmc_dargs += "--no-por --context-bound 4"
  esbmc_dargs += "--no-slice "
```

```
Statistics:           1130 Files
  correct:             962
    correct true:      178
    correct false:     784
  incorrect:            19
    incorrect true:     13
    incorrect false:     6
  unknown:             149
  Score:               628 (max: 1413)
```

2021-03-03 15:40 UTC, mikhailramalho requested changes
small nitpicks

2021-03-03 15:40 UTC, mikhailramalho commented on regression/esbmc-unix5/github_148_fail/code.cpp
> +    else if(is_array_type(it))
Thrash?

2021-03-03 15:40 UTC, mikhailramalho commented on regression/esbmc-unix5/github_148_fail/main.c.orig
> +extern int __VERIFIER_nondet_int(void);
Thrash?

2021-03-03 15:40 UTC, mikhailramalho commented on regression/esbmc-unix5/github_148_fail/test.sh
> +#!/bin/bash
Thrash?

2021-03-03 15:40 UTC, mikhailramalho commented on regression/esbmc/19_time_var_mutex_true-unreach-call/test.desc
> +CORE
the test case is name true-unreach-call, are we sure this is supposed to fail?

2021-03-03 17:49 UTC, lucasccordeiro commented on regression/esbmc-unix5/github_148_fail/code.cpp
> +    else if(is_array_type(it))
Fixed.

2021-03-03 17:49 UTC, lucasccordeiro commented on regression/esbmc-unix5/github_148_fail/main.c.orig
> +extern int __VERIFIER_nondet_int(void);
Fixed.

2021-03-03 17:49 UTC, lucasccordeiro commented on regression/esbmc-unix5/github_148_fail/test.sh
> +#!/bin/bash
Fixed.

2021-03-26 17:28 UTC, lucasccordeiro commented
This PR is already obsolete.

2021-03-26 17:28 UTC, closed without merging