Support to large integers
esbmc/esbmc pull request #404
Opened 2021-03-04 23:44 UTC by rafaelsamenezes

2022-05-05 10:43 UTC, lucasccordeiro approved these changes
LGTM.

2022-05-05 19:03 UTC, mikhailramalho requested changes

2022-05-05 19:03 UTC, mikhailramalho commented on src/util/c_typecast.cpp
> +    if(width == 128)
Can we just remove the magic number, i.e., define them in the config object?

2022-05-06 09:41 UTC, fbrausse commented on src/util/c_types.h
> +type2tc uint_type2();
uint_type[2]() have already been declared above.

2022-05-06 09:42 UTC, fbrausse commented on src/util/c_types.h
> +typet unsigned_short_int_type();
Same duplication of declaration.

2022-05-06 15:04 UTC, rafaelsamenezes commented on src/util/c_types.h
> +type2tc uint_type2();
ow, nice catch!

2022-05-06 19:48 UTC, mikhailramalho reviewed
LGTM!

2022-05-06 19:48 UTC, mikhailramalho approved these changes

2022-05-12 08:19 UTC, merged

2022-05-12 08:35 UTC, fbrausse commented on src/util/c_types.cpp
> +  return signedbv_typet(128);
Sorry, have missed this. Should we use the new config setting `int_128_width` here and in the functions below?