Cbmc test
esbmc/esbmc pull request #414
Opened 2021-03-13 19:25 UTC by rafaelsamenezes

This PR:

- converts from Boost.Test into Catch2
- brings some changes unittests from cbmc that were simple to integrate
- Closes #413

2021-03-13 19:38 UTC, mikhailramalho approved these changes
I saw some TODOs here, are they yours or from CBMC? If the latter, I believe we can remove them.

Otherwise, LGTM.

2021-03-13 19:48 UTC, lucasccordeiro approved these changes

2021-03-13 20:04 UTC, rafaelsamenezes commented
> I saw some TODOs here, are they yours or from CBMC? 

Mine I've added for methods that we may want to add in the future e.g. checking if a symbol is well formed

2021-03-13 21:30 UTC, lucasccordeiro approved these changes

2021-03-15 16:47 UTC, lucasccordeiro requested changes

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/clang-c-frontend/typecast.fuzz.cpp
> +#include "../testing-utils/util_irep.h"
Is it correct?

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/clang-c-frontend/typecast.test.cpp
> +#include "../testing-utils/util_irep.h"
Is it correct?

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/util/replace_symbol.test.cpp
> +  // REQUIRE(!r.replace(array_type)); TODO: Fix this
Shall these comments be removed?

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/util/replace_symbol.test.cpp
> +  // REQUIRE(array_type.size() == other_expr);
Shall these comments be removed?

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/util/replace_symbol.test.cpp
> +  // REQUIRE(binary.op0() == address_of_exprt(s1));
Shall these comments be removed?

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/util/replace_symbol.test.cpp
> +  //REQUIRE(to_array_type(index_expr.array().type()).size() == c);
Shall these comments be removed?

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/util/replace_symbol.test.cpp
> +  // REQUIRE(binary.op0() == address_of_exprt(s1));
Shall these comments be removed?

2021-03-15 16:47 UTC, lucasccordeiro commented on unit/util/std_expr.test.cpp
> +  /* This will not work on current implementation (and we probably shouldn't waste time on this)
Shall these comments be removed?

2021-03-17 19:49 UTC, merged