added support for parallel SMT solving
esbmc/esbmc pull request #459
Opened 2021-07-01 12:15 UTC by lucasccordeiro

This PR adds support for parallel SMT solving with the SMT solver Z3.

2021-07-01 15:33 UTC, mikhailramalho requested changes
I don't think we should abort when parallel solving is not available; it might be frustrating for the user to wait for all the symex time only to abort because of a wrong option.

Also, replace `std::endl` with `\n`.

2021-07-01 15:33 UTC, mikhailramalho commented on src/solvers/z3/z3_conv.cpp
> +    p.set("relevancy", 0U);
Is this required?

2021-07-01 18:55 UTC, rafaelsamenezes approved these changes
LGTM

2026-02-12 10:48 UTC, rafaelsamenezes commented
@lucasccordeiro how's this PR going?

2026-02-12 12:40 UTC, lucasccordeiro commented
We can close it ;-)

2026-02-12 12:40 UTC, closed without merging