[Solidity] Add line number
esbmc/esbmc pull request #628
Opened 2022-02-08 19:20 UTC by kunjsong01

1. Added line number support. 
2. Dynamic array fixes and merge.

ESBMC-Solidity is now able to give exact line number in the couterexample.

2022-02-08 19:57 UTC, lucasccordeiro requested changes
@kunjsong01: Could you please add information about the line number in the test.desc file?

2022-02-09 09:11 UTC, kunjsong01 commented
>Could you please add information about the line number in the test.desc file?

All test.desc files have been updated to include the flag `--contract <solidity source file>` for line number indications. 

Do we also want to add some additional information in test.desc for line number indication? What kind of information would it be?

2022-02-09 10:10 UTC, lucasccordeiro requested changes
@kunjsong01: once you address these comments, I'm happy to accept this PR.

2022-02-09 10:10 UTC, lucasccordeiro commented on src/langapi/language_ui.cpp
> +      //language.set_smart_contract_source(_cmdline.vm["contract"].as<std::string>());
Remove this.

2022-02-09 10:10 UTC, lucasccordeiro commented on regression/esbmc-solidity/github_dynamic_loop/test.desc
> +^VERIFICATION FAILED$
Add the line number in the regular expression.

2022-02-09 10:10 UTC, lucasccordeiro commented on src/solidity-frontend/pattern_check.cpp
> +  printf("DEBUG_TX_ORIGIN: in check_authorization_through_tx_origin\n");
Do we want to keep this debug function?

2022-02-09 10:10 UTC, lucasccordeiro commented on src/solidity-frontend/solidity_convert.cpp
> +  // TODO: debug remove before commit
Remember removing this.

2022-02-09 10:10 UTC, lucasccordeiro commented on src/solidity-frontend/solidity_convert.h
> +#include <iostream> // @@ DEBUG: remove before commit
Remove this?

2022-02-12 02:56 UTC, kunjsong01 commented
Added line numbers in all applicable test cases. 
Also removed all debug prints.

2022-02-12 04:52 UTC, merged