[options] added an option to not crash on non supported models
esbmc/esbmc pull request #657
Opened 2022-03-21 14:11 UTC by rafaelsamenezes

Added an option to make every non supported model extraction return zero. Closes: #656 

This is a draft because I will still look for some test cases on sv-benchmarks

2022-03-21 14:14 UTC, lucasccordeiro requested changes

2022-03-21 14:14 UTC, lucasccordeiro commented on src/solvers/smt/smt_conv.cpp
> +    if(options.get_bool_option("non-supported-models-as-zero"))
Shall you add a negation here?

If the user sets `--non-supported-models-as-zero`, this method will return true.

2022-03-21 15:13 UTC, rafaelsamenezes commented on src/solvers/smt/smt_conv.cpp
> +    if(options.get_bool_option("non-supported-models-as-zero"))
Oops, yes!

2022-03-21 15:46 UTC, lucasccordeiro approved these changes
@rafaelsamenezes: can you please add a regression test here?

2022-04-01 14:28 UTC, lucasccordeiro commented
@rafaelsamenezes: This is a nice PR to evaluate with the SV-COMP benchmarks.

2022-04-27 10:39 UTC, lucasccordeiro commented
@rafaelsamenezes: could you please add some regression tests here?

2022-04-27 13:46 UTC, fbrausse reviewed
There are 3 get_by_* methods in smt_convt. You may also want to put this check in https://github.com/esbmc/esbmc/blob/8a30f2f28db294b6a334f332392e1fe22c82ae8b/src/solvers/smt/smt_conv.cpp#L2695

2022-04-27 13:46 UTC, fbrausse commented on src/esbmc/options.cpp
> +    {"non-supported-models-as-zero", NULL, "if ESBMC does  as a zero"},
This message reads incomplete.

2022-05-12 09:08 UTC, lucasccordeiro commented
@rafaelsamenezes: could you please run this PR over the SV-COMP benchmarks?

2022-05-24 11:03 UTC, rafaelsamenezes commented
I've run this over sv-comp and it the only results that changed were noise. I will merge this PR.

2022-05-24 11:04 UTC, merged