Add while loop grammar construct to solidity frontend
esbmc/esbmc pull request #665
Opened 2022-04-02 15:41 UTC by correcthorsebatterystaple

This PR adds the while loop grammar for the solidity front end.

2022-04-02 21:18 UTC, kunjsong01 commented
Could you please add a while-loop test case in src/regression and run clang-format?

2022-04-03 08:48 UTC, lucasccordeiro commented
We don’t use the iostream library anymore to print messages in the console. Please take a look at other classes (e.g., in goto-symex) to see how we print messages using the fmt library.

2022-04-03 19:22 UTC, mikhailramalho requested changes
You need to fix the code style:
1. Curly brackets go into the next line
2. One-line ifs don't use curly brackets
3. Don't use iostream, use the messaget interface instead
4. the identations is two spaces, instead of tabs

2022-04-05 09:06 UTC, rafaelsamenezes commented on src/solidity-frontend/solidity_convert.cpp
> +  std::cout << std::setw(2) << json << std::endl;
If you don't want to pass down the messaget object. You can use the `default_message` for it (since this is only a dump!).

2022-04-05 09:06 UTC, rafaelsamenezes requested changes

2022-04-05 09:06 UTC, rafaelsamenezes commented on src/solidity-frontend/solidity_convert.cpp
> +#include <iostream>
remove

2022-04-05 09:06 UTC, rafaelsamenezes commented on src/solidity-frontend/solidity_convert.h
> +#include <iostream>
remove this

2022-04-06 11:17 UTC, correcthorsebatterystaple commented
Have removed print statements and methods as they were vestigial from gdb debugging

2022-04-06 12:43 UTC, lucasccordeiro approved these changes
Can you please add a test case that succeeds?

2022-04-06 12:45 UTC, lucasccordeiro commented
Could you please also rebase your PR with the master branch?

2022-04-06 14:23 UTC, rafaelsamenezes requested changes
Just some nitpicks. After that, LGTM!

2022-04-06 14:23 UTC, rafaelsamenezes commented on src/solidity-frontend/solidity_convert.cpp
> +    {
remove brackets if the `if` contains only one instruction

2022-04-06 14:23 UTC, rafaelsamenezes commented on src/solidity-frontend/solidity_convert.cpp
> +    {
remove brackets if the `if` contains only one instruction

2022-04-07 07:53 UTC, lucasccordeiro commented
@correcthorsebatterystaple: could you please rebase your branch with the master branch?

2022-04-10 19:24 UTC, merged