Fix/state var init
esbmc/esbmc pull request #680
Opened 2022-04-17 16:08 UTC by correcthorsebatterystaple

Fix state variable initialization throwing errors because of a faulty key access on the AST

2022-04-18 07:35 UTC, lucasccordeiro requested changes
@correcthorsebatterystaple: could you please add a regression test that produces `VERIFICATION FAILED`?

2022-04-18 07:36 UTC, lucasccordeiro commented
BTW, the recently added regression test fails in our CI:

```
The following tests FAILED:
	727 - regression/esbmc-solidity/github_state_init (Failed)
Errors while running CTest
```

2022-04-19 09:29 UTC, kunjsong01 requested changes

2022-04-19 09:29 UTC, kunjsong01 commented on src/solidity-frontend/solidity_convert.cpp
> +    // location variable in function body
local variable in function body?

2022-04-19 09:29 UTC, kunjsong01 commented on regression/esbmc-solidity/github_state_init/test.desc
> +contract.solast
The JSON AST file is missing in the commit.

2022-04-19 09:32 UTC, kunjsong01 commented on regression/esbmc-solidity/github_state_init/test.desc
> +^VERIFICATION SUCCESSFUL$
Would it possible to add another test case that reports "VERIFICATION FAILED"?

2022-04-25 08:20 UTC, kunjsong01 approved these changes

2022-04-25 08:22 UTC, lucasccordeiro approved these changes

2022-04-25 08:23 UTC, merged