Feature/add bool literal
esbmc/esbmc pull request #682
Opened 2022-04-17 18:08 UTC by correcthorsebatterystaple

Add boolean literal analysis for solidity frontend

2022-04-17 23:10 UTC, mikhailramalho commented on src/solidity-frontend/solidity_convert_literals.cpp
> +  if(the_value == "true")
This is correct but to make it consistent with the code style I suggest:
```
  if(the_value == "true")
  {
    dest = true_exprt();
    return false;
  }
  
  if(the_value == "false")
  {
    dest = false_exprt();
    return false;
  }

  return true;
}
```

2022-04-18 07:41 UTC, lucasccordeiro requested changes
@correcthorsebatterystaple: could you also please add more regression tests (e.g., when y is `false`)?

2022-04-19 09:42 UTC, kunjsong01 requested changes

2022-04-19 09:42 UTC, kunjsong01 commented on regression/esbmc-solidity/github_bool_literal/test.desc
> +^VERIFICATION SUCCESSFUL$
Would it be possible to add another regression test that reports "VERIFICATION FAIL"? 
Ideally, we woud like two test cases one reporting successful and the other reporting failed.

2022-04-25 08:24 UTC, kunjsong01 approved these changes

2022-04-25 08:54 UTC, merged