Fix cpp reference
esbmc/esbmc pull request #753
Opened 2022-06-15 22:16 UTC by kunjsong01

(WIP)
Implemented Rule 1 and 3 in Issue https://github.com/esbmc/esbmc/issues/736

2022-06-16 10:23 UTC, kunjsong01 commented
### Failed Regression Investigation: 
`regression/esbmc-unix2/23_picosat-846_05` failed due to unsupported type: 
```
ESBMC version 6.10.0 64-bit x86_64 linux
Target: 32-bit little-endian x86_64-unknown-linux with esbmc libc
file app.c: Parsing
file picosat.c: Parsing
Converting
### ERROR:
Conversion of unsupported clang type: "LValueReference
LValueReferenceType 0x785d800 '__builtin_va_list &'
`-TypedefType 0x7653700 '__builtin_va_list' sugar
  |-Typedef 0x752f468 '__builtin_va_list'
  `-PointerType 0x752f420 'char *'
    `-BuiltinType 0x752e900 'char'

### ERROR:
CONVERSION ERROR
```

Supposedly, lvalue reference shall be only applicable to C++. The above error happened becuase commit b168349a5592fd5e9b8865ce5494126308f5f462 moved the `clang::Type::LValueReference` case from clang-c into clang-cpp converter. 

Strangely, `LValueReferenceType` node does not exist in the parse tree ([parse_tree.c.zip](https://github.com/esbmc/esbmc/files/8917963/parse_tree.c.zip))

### More investigation TODOs:
1. Does `--parse-tree-*` show the entire tree when verifying multiple files? 
2. Why C verification contains `LValueReferenceType` node?

2022-06-16 18:34 UTC, kunjsong01 commented
We have an ongoing SV-COMP CI for this PR: https://github.com/esbmc/esbmc/actions/runs/2511001904

2022-06-17 08:08 UTC, lucasccordeiro approved these changes
I have just minor comments.

2022-06-17 08:08 UTC, lucasccordeiro commented on regression/esbmc-cpp11/reference/Reference1/main.cpp
> +  assert(r.i == 1); // fail
Should it fail? The test desc says that it should succeed instead.

2022-06-17 08:08 UTC, lucasccordeiro commented on src/clang-c-frontend/clang_c_convert.cpp
> +  if(const auto *nd = llvm::dyn_cast<clang::ValueDecl>(&d))
Add some comments?

2022-06-17 08:08 UTC, lucasccordeiro commented on src/clang-cpp-frontend/clang_cpp_convert.cpp
> +  case clang::Type::LValueReference:
Add a short explanation?

2022-06-17 08:27 UTC, rafaelsamenezes approved these changes
Just a syntax comment, after that LGTM.

2022-06-17 08:27 UTC, rafaelsamenezes commented on src/clang-c-frontend/clang_c_convert.cpp
> +    {
remove the brackets

2022-06-17 08:34 UTC, mikhailramalho requested changes
@kunjsong01 I think this patch changes the usual flow of conversion; you're changing the IR while converting it: the two-step conversion (first convert then adjust) was designed to handle cases like these.

If you need to do these operations, you need to mark the irep while converting and handle it in the adjust. Maybe you're looking for a `.lvalue` flag?

I don't recommend to merge the PR as is.

2022-06-17 08:34 UTC, mikhailramalho commented on src/clang-c-frontend/clang_c_convert.cpp
> +    if(the_type.getTypeClass() == clang::Type::LValueReference)
this can be written as `return the_type.getTypeClass() == clang::Type::LValueReference);`

2022-06-20 09:55 UTC, fbrausse approved these changes
LGTM.

I'm wondering whether there are guarantees C++ makes on references (such as always being initialized and basically its value-set being constant) we could make use of in order to do less work on them.

2022-06-20 09:55 UTC, fbrausse commented on src/clang-c-frontend/clang_c_convert.h
> +  bool is_lvalue_reference(const clang::Decl &d);
Could this be made `static` to hint that this function doesn't depend on any members of `class clang_c_convert`?

2022-06-20 09:55 UTC, fbrausse commented on src/clang-c-frontend/clang_c_convert.cpp
> +            // To make it a function argument, we need to wrap it in a "&(.)" expresson
typo: expression

2022-06-22 13:21 UTC, lucasccordeiro commented
This PR:

```
Statistics:          15648 Files
  correct:            6285
    correct true:     3799
    correct false:    2486
  incorrect:            32
    incorrect true:     15
    incorrect false:    17
  unknown:            9331
  Score:              9332 (max: 25567)
```

Master:

```
Statistics:          15648 Files
  correct:            8457
    correct true:     5137
    correct false:    3320
  incorrect:            54
    incorrect true:     25
    incorrect false:    29
  unknown:            7137
  Score:             12330 (max: 25567)
```

2022-06-22 19:36 UTC, mikhailramalho commented
Weird results.

2022-06-22 19:45 UTC, lucasccordeiro commented
Yes! Kunjian will need to check for the failing cases.

2022-06-22 19:52 UTC, mikhailramalho commented
@kunjsong01 did you check how it was implemented in v1? I've only found:
```
    case clang::Type::LValueReference:
    {
      const clang::LValueReferenceType &lvrt =
        static_cast<const clang::LValueReferenceType &>(the_type);

      const clang::QualType &pointee = lvrt.getPointeeTypeAsWritten();

      typet sub_type;
      if(get_type(pointee, sub_type))
        return true;

      // Special case, pointers to structs/unions/classes must not
      // have a copy of it, but a reference to the type
      if(sub_type.is_struct() || sub_type.is_union())
      {
        struct_union_typet t = to_struct_union_type(sub_type);
        sub_type = symbol_typet(t.tag().as_string());
      }

      new_type = gen_pointer_type(sub_type);
      new_type.set("#reference", true);
      break;
    }
```

Isn't it enough? Actually, I don't think we even need to set the "#reference" flag.

2022-06-23 09:37 UTC, lucasccordeiro commented
I have seen that @kunjsong01 has used 10 seconds as a timeout. That's why we get weird results.

I have started a new run with the standard 300 seconds:

https://github.com/esbmc/esbmc/actions/runs/2548183464

2022-06-23 09:37 UTC, lucasccordeiro commented
I have seen that @kunjsong01 has used 10 seconds as a timeout. That's why we get weird results.

I have started a new run with the standard 300 seconds:

https://github.com/esbmc/esbmc/actions/runs/2548183464

2022-06-24 10:24 UTC, lucasccordeiro commented
This PR with 300 seconds:

```
Statistics:          15648 Files
  correct:            8435
    correct true:     5124
    correct false:    3311
  incorrect:            53
    incorrect true:     24
    incorrect false:    29
  unknown:            7160
  Score:             12327 (max: 25567)
```

Master:

```
Statistics:          15648 Files
  correct:            8455
    correct true:     5128
    correct false:    3327
  incorrect:            53
    incorrect true:     24
    incorrect false:    29
  unknown:            7140
  Score:             12351 (max: 25567)
```

2022-06-26 12:50 UTC, kunjsong01 commented
>@kunjsong01 I think this patch changes the usual flow of conversion; you're changing the IR while converting it: the two-step conversion (first convert then adjust) was designed to handle cases like these.

>@kunjsong01 did you check how it was implemented in v1? I've only found:

TODOs: 
1. Check lvalue reference handler in v1. If this handler works, use this one. 
2. If v1 handler does not work, split the patch into two-step conversion.

2022-06-27 15:14 UTC, kunjsong01 commented
> @kunjsong01 did you check how it was implemented in v1? I've only found:
> 
> ```
>     case clang::Type::LValueReference:
>     {
>       const clang::LValueReferenceType &lvrt =
>         static_cast<const clang::LValueReferenceType &>(the_type);
> 
>       const clang::QualType &pointee = lvrt.getPointeeTypeAsWritten();
> 
>       typet sub_type;
>       if(get_type(pointee, sub_type))
>         return true;
> 
>       // Special case, pointers to structs/unions/classes must not
>       // have a copy of it, but a reference to the type
>       if(sub_type.is_struct() || sub_type.is_union())
>       {
>         struct_union_typet t = to_struct_union_type(sub_type);
>         sub_type = symbol_typet(t.tag().as_string());
>       }
> 
>       new_type = gen_pointer_type(sub_type);
>       new_type.set("#reference", true);
>       break;
>     }
> ```
> 
> Isn't it enough? Actually, I don't think we even need to set the "#reference" flag.

No, it's not enough. The code above generates the incorrect conversion: 
```
704 Symbol......: c:@F@main#
705 Module......: main
706 Base name...: main
707 Mode........: C (0)
708 Type........: signed int ()
709 Value.......:
710 {
711 signed int * r=(signed int *)g;    // ---> original code: int &r = g; 
712
713 r = (signed int *)1;  // ---> orginal code: r = 1;
```

But we want: 
```
signed int * r=&g;

*r = 1;
```

2022-06-27 15:24 UTC, kunjsong01 commented
> @kunjsong01 I think this patch changes the usual flow of conversion; you're changing the IR while converting it: the two-step conversion (first convert then adjust) was designed to handle cases like these.
> 
> If you need to do these operations, you need to mark the irep while converting and handle it in the adjust. Maybe you're looking for a `.lvalue` flag?
> 
> I don't recommend to merge the PR as is.

ACK. 
I thought of the two-step rule when making the changes, but I didn't go for it because I wanted to quickly test my idea as explained in https://github.com/esbmc/esbmc/issues/736#issuecomment-1156324386. 

I agree that we should stick to the two-step rule, otherwise the converter will become too messy. I'll move some conversion steps to the adjuster.

2022-06-28 13:26 UTC, kunjsong01 commented on src/clang-c-frontend/clang_c_convert.cpp
> +      val.swap(result_expr);
mark the irep and move this conversion to adjuster

2022-06-28 13:27 UTC, kunjsong01 commented on src/clang-c-frontend/clang_c_convert.cpp
> +      // get type and make a dereference subtree
mark the irep tree and move this conversion to adjuster

2022-06-28 13:29 UTC, kunjsong01 commented on src/clang-c-frontend/clang_c_convert.cpp
> +        if(stmt->getStmtClass() == clang::Stmt::DeclRefExprClass)
mark the irep and move the conversion to adjuster to handle function callsite

2022-06-28 17:17 UTC, mikhailramalho commented
Btw @kunjsong01, here's the goto program generated by the last working version of the cpp frontend:
```
        // 25 file main.cpp line 15
        class t1 * r;
        // 26 file main.cpp line 15
        r=&instance1;
        // 27 file main.cpp line 16
        ASSERT r->cpp::t1::i == 0
        // 28 file main.cpp line 17
        r->cpp::t1::i=1;
        // 29 file main.cpp line 18
        ASSERT r->cpp::t1::i == 2
```

2022-06-28 21:10 UTC, kunjsong01 commented on src/clang-c-frontend/clang_c_convert.cpp
> +      val.swap(result_expr);
Done in 80d1afc383924e5b4aef7b6651939ceb73a25982

2022-06-29 19:05 UTC, kunjsong01 commented
I tried to use the two-step conversion to deal with lvalue reference and only managed to complete it *partially* in commit 80d1afc383924e5b4aef7b6651939ceb73a25982 for lvalue reference initialisation and 4a3c7d4fd4f92f02ac6a7ab28d5f91f8385df8e7 for lvalue reference DeclExprRef in assignment, but really struggled with making further progression. 

My general feeling is that it really overcomplicates things a lot, not to mention the "reference: 1" marking gets lost during adjusting. 

Considering the test case below:
```cpp
     1	#include <cassert>
     2	void function(int &t) { t = 2;}
     3
     4	int main()
     5	{
     6	  int g;
     7	  int &r = g;
     8	  r = 1;
     9	  assert(g == 1);
    10	  function(r);
    11	  assert(r == 2);
    12	}
```

The [previous version of this patch](https://github.com/esbmc/esbmc/pull/777/files#diff-77a14a166a14947af9a9605e058ed20d935cf5200891234187cf015166925590) has a centralised place ([see line 1268 - 1280](https://github.com/esbmc/esbmc/pull/777/files#diff-77a14a166a14947af9a9605e058ed20d935cf5200891234187cf015166925590R1268-R1280)) to convert lvalue reference DeclExprRef and it generated the correct GOTO conversion: 
```c
        // 27 file main.cpp line 10 function main
     1: FUNCTION_CALL:  function(&(*r))   // ---> already converted 
        // 28 file main.cpp line 11 function main
        ASSERT *r == 2 // assertion r == 2    // ---> already converted
        // 29 file main.cpp line 11 function main
        IF !(*r == 2) THEN GOTO 2   // ---> already converted 
        // 30 file main.cpp line 11 function main
        0;
```

The current version of this patch generated the wrong GOTO program and we have to adjust more places for lvalue reference (probably more adjusting for complicated data structures in the future?)
```c
     1: FUNCTION_CALL:  function(r)    // ---> should be OK? 
        // 28 file main.cpp line 11 function main
        ASSERT (signed int)r == 2 // assertion r == 2    // ---> need to adjust typecast to dereference
        // 29 file main.cpp line 11 function main
        IF !((signed int)r == 2) THEN GOTO 2      // ---> need to adjust typecast to dereference
        // 30 file main.cpp line 11 function main
        0;
```

>@kunjsong01 I think this patch changes the usual flow of conversion; 

On second thought, we only change the usual flow of conversion for lvalue reference in the [previous version of this patch](https://github.com/esbmc/esbmc/pull/777/files#diff-77a14a166a14947af9a9605e058ed20d935cf5200891234187cf015166925590). Since all the changes are guarded by `if(is_lvalue_reference(dcl))`, it does not affect the conversion for other language constructs. 


@mikhailramalho do we have to stick to the two-step conversion strictly? It might work for other cases, but really overcomplicates things for lvalue reference. 
If we can have a centralised place to deal with lvalue referene ([e.g. just 12 lines to handle lvalue reference DeclRefExpr](https://github.com/esbmc/esbmc/pull/777/files#diff-77a14a166a14947af9a9605e058ed20d935cf5200891234187cf015166925590R1268-R1280)), why do we bother adding more lines of code in the adjuster?

2022-06-29 19:15 UTC, kunjsong01 commented
> Btw @kunjsong01, here's the goto program generated by the last working version of the cpp frontend:
> 
> ```
>         // 25 file main.cpp line 15
>         class t1 * r;
>         // 26 file main.cpp line 15
>         r=&instance1;
>         // 27 file main.cpp line 16
>         ASSERT r->cpp::t1::i == 0
>         // 28 file main.cpp line 17
>         r->cpp::t1::i=1;
>         // 29 file main.cpp line 18
>         ASSERT r->cpp::t1::i == 2
> ```

The [previous version of this patch](https://github.com/esbmc/esbmc/pull/777) generates the following GOTO program: 
```c
main (c:@F@main#):
        // 20 no location
        t1 instance1;
        // 21 no location
        FUNCTION_CALL:  t1(&instance1)
        // 22 file main.cpp line 15 function main
         t1 { signed int i; } * r;
        // 23 file main.cpp line 15 function main
        r=&instance1;
        // 24 file main.cpp line 16 function main
        ASSERT r->i == 0 // assertion r.i == 0
        // 25 file main.cpp line 16 function main
        IF !(r->i == 0) THEN GOTO 1
        // 26 file main.cpp line 16 function main
        0;
```

@mikhailramalho Does it look about right? 
`t1 { signed int i; } * r;` appears quite strange. Ideally, it should be like "t1 * r;"

2022-06-29 19:50 UTC, mikhailramalho commented
> > Btw @kunjsong01, here's the goto program generated by the last working version of the cpp frontend:
> > ```
> >         // 25 file main.cpp line 15
> >         class t1 * r;
> >         // 26 file main.cpp line 15
> >         r=&instance1;
> >         // 27 file main.cpp line 16
> >         ASSERT r->cpp::t1::i == 0
> >         // 28 file main.cpp line 17
> >         r->cpp::t1::i=1;
> >         // 29 file main.cpp line 18
> >         ASSERT r->cpp::t1::i == 2
> > ```
> 
> The [previous version of this patch](https://github.com/esbmc/esbmc/pull/777) generates the following GOTO program:
> 
> ```c
> main (c:@F@main#):
>         // 20 no location
>         t1 instance1;
>         // 21 no location
>         FUNCTION_CALL:  t1(&instance1)
>         // 22 file main.cpp line 15 function main
>          t1 { signed int i; } * r;
>         // 23 file main.cpp line 15 function main
>         r=&instance1;
>         // 24 file main.cpp line 16 function main
>         ASSERT r->i == 0 // assertion r.i == 0
>         // 25 file main.cpp line 16 function main
>         IF !(r->i == 0) THEN GOTO 1
>         // 26 file main.cpp line 16 function main
>         0;
> ```
> 
> @mikhailramalho Does it look about right? `t1 { signed int i; } * r;` appears quite strange. Ideally, it should be like "t1 * r;"

The latter is wrong, it should gen a reference instruction. 

I just had a quick look and saw that ESBMC is using the expr2c class to dump c++ code, that's why you're not seeing the reference. This patch should fix it:  [0001-Fix-using-expr2c-to-print-c-code.patch.txt](https://github.com/esbmc/esbmc/files/9013741/0001-Fix-using-expr2c-to-print-c-code.patch.txt)  (it's just a quick fix, the mode should a member class for each frontend, and get_default_symbol should just call mode).

Regarding the two-step conversion, yes we should keep using it or it'll end up like the goto conversion, wherein a bunch of "adjustments" are happening while we convert stuff: it's now very hard to decouple the functionalities and change each code slightly breaks the other.

I suggest you take a look at the old frontend and how it handles the conversion, it goes:
```
cpp_typecheckt::convert_initializer
cpp_typecheckt::reference_initializer
cpp_typecheckt::reference_binding
```
where the address_of is created to the RHS.

You don't actually need to do all the typecheck performed by these functions, as they were already done by clang and we can assume that it's legal code, so focus only on the AST changes required.

2022-06-29 19:56 UTC, kunjsong01 commented
> The latter is wrong, it should gen a reference instruction.

@mikhailramalho  Which 'reference instruction' are you referring to?

2022-06-29 19:59 UTC, mikhailramalho commented
> > The latter is wrong, it should gen a reference instruction.
> 
> @mikhailramalho Which 'reference instruction' are you referring to?

Sorry, I meant at symbol table level, with the attached patch we get:
```
Module......: main2
Base name...: main
Mode........: C++ (1)
Type........: int ()
Value.......: 
{
t1 instance1;
t1(&instance1);

struct t1 & r=instance1;
r->i == 0 ? 0 : __assert_fail(&"r.i == 0"[0], &"main2.cpp"[0], 16, &"int main()"[0]);
r->i = 1;
r->i == 2 ? 0 : __assert_fail(&"r.i == 2"[0], &"main2.cpp"[0], 18, &"int main()"[0]);
}
Flags.......: lvalue
Location....: file main2.cpp line 12
``` 

You can see the `struct t1 & r` there, now we need to check/adjust its initializer, esbmc with take care of the rest.

2022-06-30 10:23 UTC, kunjsong01 commented on src/clang-c-frontend/clang_c_convert.cpp
> +      // get type and make a dereference subtree
Tried 4a3c7d4fd4f92f02ac6a7ab28d5f91f8385df8e7 but it's making the adjust code structure too messy. 
Need to figure out a better way to adjust DeclRefExpr.

2022-06-30 17:49 UTC, kunjsong01 commented
> I suggest you take a look at the old frontend and how it handles the conversion, it goes:
cpp_typecheckt::convert_initializer
cpp_typecheckt::reference_initializer
cpp_typecheckt::reference_binding

I looked into the above functions. They seem to use lots of ESBMC's existing methods, e.g. is_reference(symbol.type) . Also, the cpp_typecheckt::reference_binding  also deals with temporaries.

Compared to these methods, my idea appears really hacky to me. Because:
1. it does not deal with temporaries
2. it may not interface well with the existing ESBMC backend, i.e. may not be able to take full advantage of the C++ verification capabilities in the backend

@mikhailramalho I think I'm going to take your patch as a starting point and re-write the entire PR based on the old frotnend to avoid backfires due to the hacky method in this PR.

2022-06-30 18:48 UTC, mikhailramalho commented
> > I suggest you take a look at the old frontend and how it handles the conversion, it goes:
> > cpp_typecheckt::convert_initializer
> > cpp_typecheckt::reference_initializer
> > cpp_typecheckt::reference_binding
> 
> I looked into the above functions. They seem to use lots of ESBMC's existing methods, e.g. is_reference(symbol.type) . Also, the cpp_typecheckt::reference_binding also deals with temporaries.

`is_reference(symbol.type)` only checks if `#reference` flag is set to true.

> 
> Compared to these methods, my idea appears really hacky to me. Because:
> 
> 1. it does not deal with temporaries
> 2. it may not interface well with the existing ESBMC backend, i.e. may not be able to take full advantage of the C++ verification capabilities in the backend
> 
> @mikhailramalho I think I'm going to take your patch as a starting point and re-write the entire PR based on the old frotnend to avoid backfires due to the hacky method in this PR.

They do a bunch of stuff because they are actually type-checking the AST, which we don't need to do as clang did that already.

The flow should be as follow: under which scenarios `convert_initializer` is called? We should replicate the checks and the transformations the old frontend does to the AST.

You also don't need to have the same structure as the old frontend, if you compare the old C frontend and the clang one, the clang one is very simplified.

2022-07-01 08:18 UTC, kunjsong01 commented
> They do a bunch of stuff because they are actually type-checking the AST, which we don't need to do as clang did that already.

> The flow should be as follow: under which scenarios convert_initializer is called? We should replicate the checks and the transformations the old frontend does to the AST.


TODO: 
1. Investigate and study the flow in `cpp_typecheckt::convert_initializer` and `cpp_typecheckt::reference_binding`. (Estimate: 0.5d) 
2. Replicate the old frontend flow and avoid unnecessary type-checking (Estimate: 2d)

2022-07-11 14:18 UTC, closed without merging

2022-07-11 14:20 UTC, kunjsong01 commented
replaced by https://github.com/esbmc/esbmc/pull/804