Added support for Jimple location
esbmc/esbmc pull request #826
Opened 2022-07-27 13:59 UTC by rafaelsamenezes

Jimple frontend is now able to generate the line location for instructions. This relies on the latest changes of the [parser](https://github.com/rafaelsamenezes/jimple2json)

2022-07-27 15:57 UTC, lucasccordeiro requested changes
@rafaelsamenezes: I have just minor comments.

2022-07-27 15:57 UTC, lucasccordeiro commented on src/jimple-frontend/AST/jimple_ast.h
> +  /// location of this instruction
"location of this instruction" -> "instruction location".

2022-07-27 15:57 UTC, lucasccordeiro commented on src/jimple-frontend/AST/jimple_method_body.cpp
> +    auto expression = stmt->to_exprt(ctx, class_name, function_name);
Add some comments here.

2022-07-27 15:57 UTC, lucasccordeiro commented on src/jimple-frontend/AST/jimple_method_body.cpp
> +    {
Remove brackets.

2022-07-27 15:57 UTC, lucasccordeiro commented on src/jimple-frontend/AST/jimple_method_body.cpp
> +      std::string location_str;
Add some comments here.

2022-07-28 09:21 UTC, lucasccordeiro approved these changes
LGTM.

2022-07-28 14:56 UTC, lucasccordeiro approved these changes
LGTM.

2022-07-28 19:40 UTC, kunjsong01 commented
LGTM

2022-07-28 19:40 UTC, kunjsong01 approved these changes

2022-07-28 19:53 UTC, merged