Green Reordering algorithm
esbmc/esbmc pull request #851
Opened 2022-09-14 13:57 UTC by rafaelsamenezes

This is the first algorithm for the canonization (normalization and renaming are missing for now) process of expr2t, which is based on this [paper](https://dl.acm.org/doi/abs/10.1145/2393596.2393665). The idea is that given an arithmetic expression, e.g `e + a + 42 + b = b + a` will convert it into `a + b + e + 42 = b + a`.

In future this will be used for the caching.

2022-09-14 15:37 UTC, lucasccordeiro requested changes

2022-09-14 15:37 UTC, lucasccordeiro commented on src/util/green_reordering.cpp
> +    break; // don't care
Shall we print some message here?

2022-09-14 15:37 UTC, lucasccordeiro commented on src/util/green_reordering.cpp
> +  assert(arith);
Shall we print a message here?

2022-09-14 15:37 UTC, lucasccordeiro commented on src/util/green_reordering.cpp
> +  assert(values.size() <= 1);
Shall we add a message here?

2022-09-14 15:37 UTC, lucasccordeiro commented on src/util/green_reordering.cpp
> +  if(expr->expr_id == expr2t::expr_ids::neg_id)
Add some comments.

2022-09-14 15:37 UTC, lucasccordeiro commented on src/util/green_reordering.cpp
> +    assert(arith);
Shall we add a message here?

2022-09-14 15:37 UTC, lucasccordeiro commented on src/util/green_reordering.cpp
> +    assert(arith);
Shall we add a message here?

2022-09-14 15:48 UTC, mikhailramalho requested changes
Nice! This is similar to what I was trying to do in the simplify branch

My comments are only related to the use of irep2 in a verbose way

2022-09-14 15:48 UTC, mikhailramalho commented on src/util/green_reordering.cpp
> +  if(expr->expr_id == expr2t::expr_ids::neg_id)
replace with `is_neg2t(expr)`

2022-09-14 15:48 UTC, mikhailramalho commented on src/util/green_reordering.cpp
> +    std::shared_ptr<arith_1op> arith;
why are you using the `std::shared_ptr<arith_1op>` directly? Can you replace this and all the similar objects with `expr2tc`?

2022-09-14 15:48 UTC, mikhailramalho commented on src/util/green_reordering.cpp
> +  else if(expr->expr_id == expr2t::expr_ids::not_id)
replace with `is_not2tc(expr)`

2022-09-19 10:02 UTC, fbrausse requested changes
While I get the benefits of term normalization, I'm not sure that adding even more algorithms that modify existing expressions is a good idea. @rafaelsamenezes Why did you choose this design instead of creating a new expression as a result of this transformation while keeping the source expression unchanged?

2022-09-19 10:02 UTC, fbrausse commented on src/util/green_reordering.h
> +  enum class TRANSVERSE_MODE
Typo: "traverse" instead of "transverse"?

2022-09-19 10:02 UTC, fbrausse commented on src/util/green_reordering.h
> +  void transverse_binop(
Typo. Other members below, too.

2022-09-19 10:02 UTC, fbrausse commented on unit/irep2/cache_fuzz_utils.cpp
> +  const char range = z - a;
`z-a+1` as you appearently want to include `'z'`. Also, you could just make this function `static` and avoid all the anon namespace syntax.

2022-09-19 10:02 UTC, fbrausse commented on unit/irep2/cache_fuzz_utils.h
> + * 00abc%a => a + b + c == a => (EQUAL (ADD (A) (ADD) (B) (C))) (A))
This looks pretty weird to me. If you want to avoid precedence via brackets, there is [polish notation](https://en.wikipedia.org/wiki/Polish_notation) for that. It seems like you used a bit of that, but not quite. Also I don't understand what `% SYMBOLS` means. Please clarify the syntax of this string.

2022-09-19 10:02 UTC, fbrausse commented on src/util/green_reordering.cpp
> +  // 2. Order it in crescent order
What do you mean by "crescent order"? To me it looks like descending order.

2022-09-19 10:02 UTC, fbrausse commented on src/util/green_reordering.h
> +  typedef std::vector<constant_int2tc> values_vec;
Please refrain from introducing unnecessary typedefs. It is hard to reason about code when types are not clear. The fact that you repeat these two types a few times, and every time together, is a hint that maybe values of both should be paired in a separate type.

2026-05-18 17:28 UTC, closed without merging