Forward Condition Slicer
esbmc/esbmc pull request #858
Opened 2022-11-04 16:03 UTC by rafaelsamenezes

This is a static slicer to be applied for the Forward Condition only. The main idea is to remove loops that do not contribute for the reachability of any assertions.  As this is added at goto program level, it will only work for explicit user assertions. Also, we can't simplify if there is any pointer unless I implement a points-to analysis.

This should make esbmc able to prove correctness in programs such as:

```c
int main() {
  while(1);
  assert(0);
}
```

The flow is the following:

1. Run an Abstract Interpretation over the program, using the dependencies for every variable at each state
2. For each function run a goto algorithm, first in backwards to store dependencies for IF, ASSERT, ASSUME, RETURN and FUNCTION_CALL
3. Same as 2, now forward... removing unecessary instructions
4. At each loop, remove if they are trivial (only contains skips).

2022-11-04 16:41 UTC, mikhailramalho commented
Interesting. Why not move it `esbmc_parseoptionst::process_goto_program` and do something like: 
`if(cmdline.isset("forward-condition") slicer.run(g);`, maybe before inlining?

There is a call to `remove_skip` on `esbmc_parseoptionst::process_goto_program`, so you don't have to.

2023-04-24 11:02 UTC, lucasccordeiro requested changes
@rafaelsamenezes: could you also run this PR over the sv-comp benchmarks?

2023-04-24 11:02 UTC, lucasccordeiro commented on src/esbmc/esbmc_parseoptions.cpp
> +    log_status("Trying to apply Forward Slicer...");
Can you improve this message? "Try" is not an appropriate verb :-)

2023-04-24 11:02 UTC, lucasccordeiro commented on src/esbmc/esbmc_parseoptions.cpp
> +      slicer.run(g);
Can you add comments to this block?

2023-04-24 11:02 UTC, lucasccordeiro commented on src/esbmc/esbmc_parseoptions.cpp
> +      log_status("Unable to slice");
Why? Can you give further explanation here?

2023-04-24 11:02 UTC, lucasccordeiro commented on src/esbmc/esbmc_parseoptions.cpp
> +  bmct bmc(g, opts, context);
Shall we keep 'goto_functions'? It is better than just 'g'.

2023-04-24 11:02 UTC, lucasccordeiro commented on src/esbmc/options.cpp
> +    {"forward-slicer", NULL, "attempt to slice loops that don't affect VCCs"},
why "attempt"? we should use a better verb here. Something like:

`Slice loops with XXX that do not affect VCCs`

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +// TODO: Move this to irep2_utils
Shall we move it to this PR?

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +  // Hack: This should prevent the atexit handled (Needed as we don't support pointers)
Hum... that's bad...  Don't we have a better solution here?

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +  if(is_pointer_type(assignment.target->type))
Shall we move this code to an earlier position in this method?

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +     throw "TODO: points-to analysis";
Shall we use our log function?

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +void slicer_domaint::declaration(const expr2tc &e)
Add some comments here.

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +void slicer_domaint::transform(
Add some comments.

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +bool slicer_domaint::join(const slicer_domaint &b)
Add some comments.

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +bool forward_slicer::runOnProgram(goto_functionst &F)
Add some comments.

2023-04-24 11:02 UTC, lucasccordeiro commented on src/goto-programs/forward_slicer.cpp
> +bool forward_slicer::runOnFunction(std::pair<const dstring, goto_functiont> &F)
Add some comments.

2023-04-28 12:58 UTC, rafaelsamenezes commented on src/goto-programs/forward_slicer.cpp
> +void slicer_domaint::transform(
These came from the default ait

2023-04-28 12:59 UTC, rafaelsamenezes commented on src/goto-programs/forward_slicer.cpp
> +bool forward_slicer::runOnProgram(goto_functionst &F)
These came from the default ait

2023-04-28 12:59 UTC, rafaelsamenezes commented on src/goto-programs/forward_slicer.cpp
> +bool forward_slicer::runOnFunction(std::pair<const dstring, goto_functiont> &F)
These came from the default algorithmst

2023-04-28 13:10 UTC, lucasccordeiro approved these changes

2026-05-18 17:38 UTC, mikhailramalho commented
Closing as part of stale-branch cleanup.

This PR has been open since 2023-04-30 with no activity. The forward slicer concept it introduces is tracked in issue #992 ("[slicer] Remove loops that do not contribute to checking a given property"), which references this PR. Closing the PR and deleting the branch — anyone reviving the work should start from a fresh implementation against current master (the slicer has moved on substantially since 2023).

The branch will be deleted; commits remain reachable via this PR's history.

2026-05-18 17:38 UTC, closed without merging