Multiple inheritance
esbmc/esbmc pull request #884
Opened 2023-01-24 19:38 UTC by kunjsong01

I continued my development based on the branch `split-inheritance` in https://github.com/esbmc/esbmc/pull/882 

**N.B. When https://github.com/esbmc/esbmc/pull/882  is merged, this PR needs a rebase.** 

Enables test case inheritance01 (without iostreams): 
```cpp
#include <cassert>

// Base class Shape
class Shape
{
   public:
      void setWidth(int w){
         width = w;
      }
      void setHeight(int h){
         height = h;
      }
   protected:
      int width;
      int height;
};

// Base class PaintCost
class PaintCost
{
   public:
      int getCost(int area){
         return area * 70;
      }
};

// Derived class
class Rectangle: public Shape, public PaintCost
{
   public:
      int getArea(){
         return (width * height);
      }
};

int main(void)
{
   Rectangle Rect;
   int area;
   int cost;

   Rect.setWidth(5);
   Rect.setHeight(7);

   area = Rect.getArea();
   cost = Rect.getCost(area);
   assert(cost == 2450); // PASS
   assert(cost == 0); // FAIL

   return 0;
}
```

Also fixed bugs in a bunch of test cases from esbmc-cpp11/reference and esbmc-cpp11/constructors.

2023-01-24 19:50 UTC, lucasccordeiro requested changes
Minor comments.

2023-01-24 19:50 UTC, lucasccordeiro commented on src/clang-c-frontend/clang_c_convert.cpp
> +  // TODO: Fix me when we have a test case using C++ unioin.
"unioin" -> "union"

2023-01-24 19:50 UTC, lucasccordeiro commented on src/clang-c-frontend/clang_c_convert.cpp
> +      if(attr->getKind() == clang::attr::Aligned)
Add comments for each case.

2023-01-24 19:50 UTC, lucasccordeiro commented on src/util/show_symbol_table.cpp
> +    {
Shall we use our log function to report these messages?

2023-01-30 16:58 UTC, lucasccordeiro approved these changes
LGTM.

2023-02-01 09:58 UTC, rafaelsamenezes approved these changes

2023-02-01 11:14 UTC, shmarovfedor approved these changes

2023-02-01 11:22 UTC, merged