Fix WinCI
esbmc/esbmc pull request #911
Opened 2023-02-21 11:55 UTC by Anthonysdu

2023-02-21 14:05 UTC, lucasccordeiro approved these changes

2023-02-21 14:11 UTC, rafaelsamenezes requested changes
minor changes required

2023-02-21 14:11 UTC, rafaelsamenezes commented on .github/workflows/release.yml
> -        cpack -G ZIP -C RelWithDebInfo
Add back `cpack`

2023-02-21 14:20 UTC, fbrausse commented on src/c2goto/CMakeLists.txt
> +    set (inputs clib64f_config)
There seems to be a mismatch here: disabling "the 32-bit libs" also disables the `clib64_config` (without `f`).

2023-02-21 14:50 UTC, fbrausse commented on src/c2goto/cprover_library.cpp
>    extern const unsigned int clib64_buf_size;
You'll also want to enable the corresponding symbols here...

2023-02-21 14:50 UTC, fbrausse commented on src/c2goto/cprover_library.cpp
> +    {&clib64_fp_buf[0], clib64_fp_buf_size},
... and here.

2023-02-21 16:25 UTC, fbrausse commented
What's the purpose of selectively disabling particular pre-built operational models like the 32-bit ones? Is it related to Windows in some way? If so, is it because 32-bit code is unsupported by ESBMC on Windows, in which case shouldn't the `--32` switch also be disabled there or is there another reason?

2023-02-21 16:41 UTC, Anthonysdu commented
> What's the purpose of selectively disabling particular pre-built operational models like the 32-bit ones? Is it related to Windows in some way? If so, is it because 32-bit code is unsupported by ESBMC on Windows, in which case shouldn't the `--32` switch also be disabled there or is there another reason?

@rafaelsamenezes Could you explain why we set this build option?

2023-02-21 17:33 UTC, rafaelsamenezes commented
> @rafaelsamenezes Could you explain why we set this build option?

@Anthonysdu In my previous branch was to build with LLVM 14 in Windows as it was causing issues. You can revert it, it won't affect this PR since you are still relying on LLVM 11.

> If so, is it because 32-bit code is unsupported by ESBMC on Windows, in which case shouldn't the --32 switch also be disabled there or is there another reason?

@fbrausse You are correct, the switch needs to be removed as well.

2023-02-22 00:54 UTC, lucasccordeiro commented
@Anthonysdu : can you please rebase this branch with the master branch?

2023-02-22 07:11 UTC, lucasccordeiro commented
@fbrausse and @rafaelsamenezes : can I ask you whether you have further comments for this PR?

2023-02-22 08:34 UTC, fbrausse approved these changes
LGTM.

@Anthonysdu maybe a small hint for future PRs: the git history is quite important for future development and fixing bugs, the more info about the actual changes and intention you put into the commit message, the better. The info what files are changed by a commit is not necessary there as it can easily be obtained with `git whatchanged`. You can also use `git revert` or `git rebase -i` to revert a previous commit.

2023-02-22 08:38 UTC, merged