Guard fix
esbmc/esbmc pull request #974
Opened 2023-04-18 16:47 UTC by Anthonysdu

This PR is the fix of the concurrency flag '--no-goto-merge', we add the guard of the previous active thread after a context switch. Because the new active thread runs under the previous guard condition (assumes it is true) while we didn't guard it in the formula.

2023-04-18 21:23 UTC, lucasccordeiro requested changes
@Anthonysdu: could please add some regression tests?

Can you also run this PR over the SV-COMP concurrency benchmarks?

2023-04-18 21:23 UTC, lucasccordeiro commented on src/goto-symex/execution_state.cpp
> +  //implies2tc assumpt(guard_expr, parent_guard);
You can remove this line.

2023-04-18 21:23 UTC, lucasccordeiro commented on src/goto-symex/execution_state.cpp
> +  //target->assumption(
You can remove this line.

2023-04-18 21:23 UTC, lucasccordeiro commented on src/goto-symex/execution_state.cpp
> +  //  guardt().as_expr(), assumpt, get_active_state().source, first_loop);
You can remove this line.

2023-04-18 21:28 UTC, Anthonysdu commented
> MP concurrency benchmarks

Yes, I am running the benchmarks with 15mins limit on the fmserver.

I will add some regresstion tests later.

2023-04-19 20:23 UTC, lucasccordeiro commented
@Anthonysdu: Can I ask you whether you have the results of this PR?

2023-04-20 08:25 UTC, Anthonysdu commented
> @Anthonysdu: Can I ask you whether you have the results of this PR?

@lucasccordeiro : I have checked it in the morning, and It is still runnning, but will finfish soon.

2023-04-20 08:28 UTC, lucasccordeiro approved these changes

2023-04-20 09:41 UTC, lucasccordeiro commented
The results of the master are:

```
Statistics:          689 Files
   correct:            435
     correct true:     145
     correct false:    290
   incorrect:            20
     incorrect true:     10
    incorrect false:     10
   Score:              100 (max: 1036)
```

The results of this PR:

```
Statistics:          689 Files
   correct:            322
     correct true:     123
     correct false:    199
   incorrect:            6
     incorrect true:     6
    incorrect false:     0
   Score:              253 (max: 1036)
```

2023-04-20 09:42 UTC, merged

2023-04-21 19:19 UTC, Anthonysdu commented
> The results of the master are:
> 
> ```
> Statistics:          689 Files
>    correct:            435
>      correct true:     145
>      correct false:    290
>    incorrect:            20
>      incorrect true:     10
>     incorrect false:     10
>    Score:              100 (max: 1036)
> ```
> 
> The results of this PR:
> 
> ```
> Statistics:          689 Files
>    correct:            322
>      correct true:     123
>      correct false:    199
>    incorrect:            6
>      incorrect true:     6
>     incorrect false:     0
>    Score:              253 (max: 1036)
> ```

The result with 15 mins:

> Statistics:            689 Files
>   correct:             434
>     correct true:      144
>     correct false:     290
>   incorrect:            10
>     incorrect true:     10
>     incorrect false:     0
>   unknown:             245
>   Score:               258 (max: 1036)

It looks like the guard fix removes all incorrect false, and with incorrect true onchanged.

For the incorrect true, now I have investiaged two reasons:
1. Insufficient context bounds.
2. Guard problems for atomic operations.